using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Playserv.Modules;
using UnityEditor;

namespace Playserv.Editor
{
    internal static class PlayServGeneratedCompatibilityLayer
    {
        private const string ThisScriptSuffix = "/Editor/Modules/PlayServGeneratedCompatibilityLayer.cs";
        private const string CompatibilityRelativePath = "Runtime/Generated/Compatibility/PlayServCompatibility.g.cs";
        private const string ModuleRegistryRelativePath = "Runtime/Generated/Modules/PlayServModuleRegistry.g.cs";
        private const string ModuleManifestRelativePath = "Runtime/Modules/Contracts/Generated/PlayServGeneratedModuleManifest.g.cs";
        private const string GeneratedEventsApiExtensionsAssetPath = "Assets/Shared/Generated/Events/PlayServ.EventsApiExtensions.g.cs";
        private const string GeneratedEventsAdapterExtensionsAssetPath = "Assets/Shared/Generated/Events/EventsAdapterExtensions.g.cs";

        private static PlayServPackageRoot _packageRoot;

        public static void SyncNow()
        {
            PlayServModuleGraphSynchronizer.SyncNow();
        }

        internal static void SyncNow(bool refreshAssetDatabase)
        {
            PlayServModuleGraphSynchronizer.SyncNow(refreshAssetDatabase);
        }

        internal static bool SyncGeneratedFiles(PlayServRuntimeModuleState runtimeState, bool importAssets)
        {
            var context = PlayServModuleCodegenRegistry.Build(runtimeState);
            var changed = false;

            changed |= WriteIfChanged(CompatibilityRelativePath, GenerateCompatibility(context), importAssets);
            changed |= WriteIfChanged(ModuleRegistryRelativePath, GenerateModuleRegistry(context), importAssets);
            changed |= WriteIfChanged(ModuleManifestRelativePath, GenerateRuntimeManifest(), importAssets);
            changed |= SyncGeneratedEventsOutput(importAssets);

            return changed;
        }

        private static bool SyncGeneratedEventsOutput(bool importAssets)
        {
            if (!PlayServGeneratedEventsOutputRegistry.TrySync(out var changed))
                return SyncDisabledGeneratedEventsOutput(importAssets);

            return changed;
        }

        private static bool SyncDisabledGeneratedEventsOutput(bool importAssets)
        {
            var changed = false;
            changed |= WriteAssetPathIfChanged(GeneratedEventsApiExtensionsAssetPath, GenerateDisabledEventsApiExtensionsCode(), importAssets);
            changed |= WriteAssetPathIfChanged(GeneratedEventsAdapterExtensionsAssetPath, GenerateDisabledEventsAdapterExtensionsCode(), importAssets);
            return changed;
        }

        private static string GenerateDisabledEventsApiExtensionsCode()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace Playserv.Wrapper");
            sb.AppendLine("{");
            sb.AppendLine("    public static class PlayServEventsApiExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");
            return sb.ToString();
        }

        private static string GenerateDisabledEventsAdapterExtensionsCode()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace Playserv.Events");
            sb.AppendLine("{");
            sb.AppendLine("    public static class EventsAdapterExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");
            return sb.ToString();
        }

        private static string GenerateCompatibility(PlayServModuleCodegenContext context)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");

            var usings = new List<string>(context.CompatibilityUsings);
            if (context.HasLocalExecutionFactory)
            {
                AddUnique(usings, "System");
                AddUnique(usings, "Playserv.Proxy.Common");
            }

            usings.Sort(StringComparer.Ordinal);
            for (var i = 0; i < usings.Count; i++)
                sb.Append("using ").Append(usings[i]).AppendLine(";");

            if (usings.Count > 0)
                sb.AppendLine();

            sb.AppendLine("namespace Playserv.Wrapper");
            sb.AppendLine("{");
            AppendPlayServFacade(sb, context.FacadeMembers);

            if (context.HasLocalExecutionFactory)
            {
                sb.AppendLine();
                AppendLocalExecutionDispatch(sb, context.LocalExecutionFactoryExpression);
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendPlayServFacade(StringBuilder sb, IReadOnlyList<string[]> facadeMembers)
        {
            sb.AppendLine("    public static partial class PlayServ");
            sb.AppendLine("    {");

            for (var i = 0; i < facadeMembers.Count; i++)
            {
                if (i > 0)
                    sb.AppendLine();

                AppendIndentedLines(sb, facadeMembers[i], "        ");
            }

            sb.AppendLine("    }");
        }

        private static void AppendLocalExecutionDispatch(StringBuilder sb, string factoryExpression)
        {
            sb.AppendLine("    internal static partial class PlayServCommandDispatchFactory");
            sb.AppendLine("    {");
            sb.AppendLine("        static partial void TryCreateModuleDispatch(ref IPlayServCommandDispatch dispatch)");
            sb.AppendLine("        {");
            sb.AppendLine("            var localExecution = CreateLocalExecution();");
            sb.AppendLine("            if (localExecution != null)");
            sb.AppendLine("                dispatch = new PlayServLocalExecutionCommandDispatch(localExecution);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static ILocalCommandExecution CreateLocalExecution()");
            sb.AppendLine("        {");
            sb.Append("            return ").Append(factoryExpression).AppendLine(";");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal sealed class PlayServLocalExecutionCommandDispatch : IPlayServCommandDispatch");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly ILocalCommandExecution _localExecution;");
            sb.AppendLine();
            sb.AppendLine("        public PlayServLocalExecutionCommandDispatch(ILocalCommandExecution localExecution)");
            sb.AppendLine("        {");
            sb.AppendLine("            _localExecution = localExecution ?? throw new ArgumentNullException(nameof(localExecution));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public object LocalExecution => _localExecution;");
            sb.AppendLine();
            sb.AppendLine("        public bool TryHandleCommand<T>(T command, string moduleName, bool hasRuntimeInstance)");
            sb.AppendLine("        {");
            sb.AppendLine("            return _localExecution.TryHandleCommand(command, moduleName, hasRuntimeInstance);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static string GenerateModuleRegistry(PlayServModuleCodegenContext context)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace Playserv.Modules");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class PlayServModuleRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        static partial void RegisterGenerated(PlayServModuleHost host)");
            sb.AppendLine("        {");

            for (var i = 0; i < context.RuntimeRegistrations.Count; i++)
            {
                var registration = context.RuntimeRegistrations[i];
                sb.Append("            host.Register(new global::")
                    .Append(registration.RuntimeModuleTypeName)
                    .AppendLine("());");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GenerateRuntimeManifest()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace Playserv.Modules");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class PlayServGeneratedModuleManifest");
            sb.AppendLine("    {");
            sb.AppendLine("        public static PlayServModuleManifestEntry[] Build()");
            sb.AppendLine("        {");
            sb.AppendLine("            return new[]");
            sb.AppendLine("            {");

            var modules = PlayServModuleManifest.RuntimeModules;
            for (var i = 0; i < modules.Count; i++)
            {
                AppendGeneratedManifestEntry(sb, modules[i]);
                sb.AppendLine(i + 1 < modules.Count ? "                )," : "                )");
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static PlayServModuleManifestEntry Module(");
            sb.AppendLine("            string id,");
            sb.AppendLine("            int order,");
            sb.AppendLine("            string label,");
            sb.AppendLine("            string description,");
            sb.AppendLine("            string disableDefine,");
            sb.AppendLine("            bool defaultEnabled,");
            sb.AppendLine("            bool isServerModule,");
            sb.AppendLine("            bool visibleInSettings,");
            sb.AppendLine("            bool visibleInExport,");
            sb.AppendLine("            string[] assetPaths,");
            sb.AppendLine("            string[] dependencyIds,");
            sb.AppendLine("            string[] hiddenDependencyAssetPaths,");
            sb.AppendLine("            string[] hiddenDependencyModuleIds,");
            sb.AppendLine("            string rootAssemblyReference,");
            sb.AppendLine("            string[] profiles)");
            sb.AppendLine("        {");
            sb.AppendLine("            return new PlayServModuleManifestEntry(");
            sb.AppendLine("                id,");
            sb.AppendLine("                label,");
            sb.AppendLine("                description,");
            sb.AppendLine("                disableDefine,");
            sb.AppendLine("                defaultEnabled,");
            sb.AppendLine("                isServerModule,");
            sb.AppendLine("                visibleInSettings,");
            sb.AppendLine("                visibleInExport,");
            sb.AppendLine("                assetPaths,");
            sb.AppendLine("                dependencyIds,");
            sb.AppendLine("                hiddenDependencyAssetPaths,");
            sb.AppendLine("                hiddenDependencyModuleIds,");
            sb.AppendLine("                rootAssemblyReference,");
            sb.AppendLine("                order,");
            sb.AppendLine("                profileIds: profiles);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string[] Values(params string[] values)");
            sb.AppendLine("        {");
            sb.AppendLine("            return values ?? Array.Empty<string>();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendGeneratedManifestEntry(StringBuilder sb, PlayServModuleManifestEntry module)
        {
            sb.AppendLine("                Module(");
            sb.Append("                    ").Append(QuoteCSharpString(module.Id)).AppendLine(",");
            sb.Append("                    ").Append(module.Order).AppendLine(",");
            sb.Append("                    ").Append(QuoteCSharpString(module.Label)).AppendLine(",");
            sb.Append("                    ").Append(QuoteCSharpString(module.Description)).AppendLine(",");
            sb.Append("                    ").Append(QuoteCSharpString(module.DisableDefine)).AppendLine(",");
            sb.Append("                    ").Append(module.DefaultEnabled ? "true" : "false").AppendLine(",");
            sb.Append("                    ").Append(module.IsServerModule ? "true" : "false").AppendLine(",");
            sb.Append("                    ").Append(module.VisibleInSettings ? "true" : "false").AppendLine(",");
            sb.Append("                    ").Append(module.VisibleInExport ? "true" : "false").AppendLine(",");
            AppendGeneratedStringArray(sb, module.AssetPaths, trailingComma: true);
            AppendGeneratedStringArray(sb, module.DependencyIds, trailingComma: true);
            AppendGeneratedStringArray(sb, module.HiddenDependencyAssetPaths, trailingComma: true);
            AppendGeneratedStringArray(sb, module.HiddenDependencyModuleIds, trailingComma: true);
            sb.Append("                    ").Append(QuoteCSharpString(module.RootAssemblyReference)).AppendLine(",");
            AppendGeneratedStringArray(sb, module.ProfileIds, trailingComma: false);
        }

        private static void AppendGeneratedStringArray(StringBuilder sb, IReadOnlyList<string> values, bool trailingComma)
        {
            sb.Append("                    Values(");
            for (var i = 0; i < values.Count; i++)
            {
                if (i > 0)
                    sb.Append(", ");

                sb.Append(QuoteCSharpString(values[i]));
            }

            sb.Append(')');
            if (trailingComma)
                sb.Append(',');

            sb.AppendLine();
        }

        private static void AppendIndentedLines(StringBuilder sb, IReadOnlyList<string> lines, string indentation)
        {
            for (var i = 0; i < lines.Count; i++)
            {
                if (string.IsNullOrEmpty(lines[i]))
                    sb.AppendLine();
                else
                    sb.Append(indentation).AppendLine(lines[i]);
            }
        }

        private static void AddUnique(ICollection<string> values, string value)
        {
            if (!values.Contains(value))
                values.Add(value);
        }

        private static string QuoteCSharpString(string value)
        {
            return "\"" + (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n") + "\"";
        }

        private static bool WriteIfChanged(string relativePath, string contents, bool importAsset)
        {
            if (!TryGetPackageRoot(out var packageRoot))
                return false;

            var path = packageRoot.ToAbsolutePath(relativePath);
            return WriteAbsolutePathIfChanged(path, contents, importAsset);
        }

        private static bool WriteAssetPathIfChanged(string assetPath, string contents, bool importAsset)
        {
            var path = PlayServPackagePathResolver.ToAbsoluteAssetPath(assetPath);
            return WriteAbsolutePathIfChanged(path, contents, importAsset);
        }

        private static bool WriteAbsolutePathIfChanged(string path, string contents, bool importAsset)
        {
            var directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            contents = NormalizeLineEndings(contents);
            if (File.Exists(path) && NormalizeLineEndings(File.ReadAllText(path)) == contents)
                return false;

            File.WriteAllText(path, contents);
            if (importAsset)
                AssetDatabase.ImportAsset(ToAssetPath(path), ImportAssetOptions.ForceUpdate);
            return true;
        }

        private static string NormalizeLineEndings(string value)
        {
            return (value ?? string.Empty).Replace("\r\n", "\n").Replace("\r", "\n");
        }

        private static bool TryGetPackageRoot(out PlayServPackageRoot packageRoot)
        {
            if (_packageRoot != null)
            {
                if (_packageRoot.Exists)
                {
                    packageRoot = _packageRoot;
                    return true;
                }

                _packageRoot = null;
            }

            if (!PlayServPackagePathResolver.TryResolveRootForScript(
                nameof(PlayServGeneratedCompatibilityLayer),
                ThisScriptSuffix,
                out packageRoot))
            {
                return false;
            }

            _packageRoot = packageRoot;
            return true;
        }

        private static string ToAssetPath(string absolutePath)
        {
            return TryGetPackageRoot(out var packageRoot)
                ? packageRoot.ToAssetPath(absolutePath)
                : PlayServPackagePathResolver.ToProjectAssetPath(absolutePath);
        }
    }

    [InitializeOnLoad]
    internal static class PlayServModuleGraphSynchronizer
    {
        private static bool _syncQueued;

        static PlayServModuleGraphSynchronizer()
        {
            QueueSync();
        }

        public static void QueueSync()
        {
            if (_syncQueued)
                return;

            _syncQueued = true;
            EditorApplication.delayCall += SyncNow;
        }

        public static void SyncNow()
        {
            SyncNow(refreshAssetDatabase: true);
        }

        internal static void SyncNow(bool refreshAssetDatabase)
        {
            _syncQueued = false;

            PlayServModuleManifestJsonRegistry.Reload();
            PlayServEditorModuleAvailability.SyncUnavailableModuleDefines();
            var state = LoadActiveState();

            var changed = false;
            changed |= PlayServCoreAssemblyReferenceSync.Sync(state, importAssets: refreshAssetDatabase);
            changed |= PlayServGeneratedCompatibilityLayer.SyncGeneratedFiles(state, importAssets: refreshAssetDatabase);

            if (changed && refreshAssetDatabase && !EditorApplication.isCompiling)
                AssetDatabase.Refresh();
        }

        internal static PlayServRuntimeModuleState LoadActiveState()
        {
            var state = PlayServRuntimeModuleDefines.LoadUserPreferenceState();
            PlayServEditorModuleAvailability.NormalizeAvailableRuntimeState(state);
            PlayServRuntimeModuleDefines.NormalizeDependencies(state);
            return state;
        }
    }

    internal sealed class PlayServGeneratedCompatibilityAssetPostprocessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            if (TouchesModuleLayout(importedAssets) ||
                TouchesModuleLayout(deletedAssets) ||
                TouchesModuleLayout(movedAssets) ||
                TouchesModuleLayout(movedFromAssetPaths))
            {
                PlayServModuleGraphSynchronizer.SyncNow();
            }
        }

        private static bool TouchesModuleLayout(string[] paths)
        {
            if (paths == null)
                return false;

            for (var i = 0; i < paths.Length; i++)
            {
                var path = (paths[i] ?? string.Empty).Replace('\\', '/');
                if (!PlayServPackagePathResolver.TryGetPackageRelativeAssetPath(path, out var relativePath))
                    continue;

                if (relativePath.StartsWith("Runtime/Modules/", StringComparison.OrdinalIgnoreCase) ||
                    relativePath.StartsWith("Runtime/Proxy/Modules/", StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(relativePath, "Runtime/Playserv.Runtime.asmdef", StringComparison.OrdinalIgnoreCase) ||
                    relativePath.StartsWith("Editor/Events/", StringComparison.OrdinalIgnoreCase) ||
                    relativePath.StartsWith("Editor/ModelGenerator/", StringComparison.OrdinalIgnoreCase) ||
                    relativePath.StartsWith("Editor/CodeGenerator/", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }

            return false;
        }
    }
}
