using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Playserv.Modules;
using UnityEditor;
using UnityEngine;

namespace Playserv.Editor
{
    [InitializeOnLoad]
    internal static class PlayServGeneratedCompatibilityLayer
    {
        private const string PackageFolderName = "playserv-unity-sdk";
        private const string ThisScriptSuffix = "/Editor/Modules/PlayServGeneratedCompatibilityLayer.cs";
        private const string CompatibilityRelativePath = "Runtime/Generated/Compatibility/PlayServCompatibility.g.cs";
        private const string ModuleRegistryRelativePath = "Runtime/Generated/Modules/PlayServModuleRegistry.g.cs";
        private const string GeneratedEventsApiExtensionsAssetPath = "Assets/Shared/Generated/Events/PlayServ.EventsApiExtensions.g.cs";
        private const string GeneratedEventsAdapterExtensionsAssetPath = "Assets/Shared/Generated/Events/EventsAdapterExtensions.g.cs";
        private const string SpawnCompileGuard = "!PLAYSERV_MODULE_DISABLED_EVENTS && !PLAYSERV_MODULE_DISABLED_SPAWN";

        private static string _packageRootPath;
        private static bool _syncQueued;

        static PlayServGeneratedCompatibilityLayer()
        {
            QueueSync();
        }

        public static void SyncNow()
        {
            SyncNow(refreshAssetDatabase: true);
        }

        internal static void SyncNow(bool refreshAssetDatabase)
        {
            _syncQueued = false;

            PlayServCoreAssemblyReferenceSync.Sync(importAssets: refreshAssetDatabase);
            var state = BuildState();

            var changed = false;

            changed |= WriteIfChanged(CompatibilityRelativePath, GenerateCompatibility(state));
            changed |= WriteIfChanged(ModuleRegistryRelativePath, GenerateModuleRegistry(state));
            changed |= SyncGeneratedEventsOutput();

            if (changed && refreshAssetDatabase && !EditorApplication.isCompiling)
                AssetDatabase.Refresh();
        }

        private static void QueueSync()
        {
            if (_syncQueued)
                return;

            _syncQueued = true;
            EditorApplication.delayCall += SyncNow;
        }

        private static bool SyncGeneratedEventsOutput()
        {
            var generatorType = Type.GetType("Playserv.Events.Editor.EventsCodeGenerator, Playserv.Editor.Events", throwOnError: false);
            var syncMethod = generatorType?.GetMethod(
                "SyncGeneratedOutputForCurrentState",
                System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);

            if (syncMethod == null)
                return SyncDisabledGeneratedEventsOutput();

            var result = syncMethod.Invoke(null, null);
            return result is bool changed && changed;
        }

        private static bool SyncDisabledGeneratedEventsOutput()
        {
            var changed = false;
            changed |= WriteAssetPathIfChanged(GeneratedEventsApiExtensionsAssetPath, GenerateDisabledEventsApiExtensionsCode());
            changed |= WriteAssetPathIfChanged(GeneratedEventsAdapterExtensionsAssetPath, GenerateDisabledEventsAdapterExtensionsCode());
            return changed;
        }

        private static string GenerateDisabledEventsApiExtensionsCode()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace Playserv.Wrapper");
            sb.AppendLine("{");
            sb.AppendLine("    public static class PlayServEventsApiExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");
            return sb.ToString();
        }

        private static string GenerateDisabledEventsAdapterExtensionsCode()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace Playserv.Events");
            sb.AppendLine("{");
            sb.AppendLine("    public static class EventsAdapterExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");
            return sb.ToString();
        }

        private static PlayServGeneratedModuleState BuildState()
        {
            var runtimeState = PlayServRuntimeModuleDefines.Load();
            PlayServEditorModuleAvailability.NormalizeAvailableRuntimeState(ref runtimeState);
            PlayServRuntimeModuleDefines.NormalizeDependencies(ref runtimeState);

            return new PlayServGeneratedModuleState(
                events: runtimeState.Events,
                data: runtimeState.Data,
                rpcCore: runtimeState.Rpc || runtimeState.Server,
                clientRpc: runtimeState.Rpc,
                server: runtimeState.Server,
                clientExecution: runtimeState.ClientExecution,
                spawn: runtimeState.Spawn && runtimeState.Events,
                pulse: runtimeState.Pulse);
        }

        private static string GenerateCompatibility(PlayServGeneratedModuleState state)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");

            var usings = BuildCompatibilityUsings(state);
            for (var i = 0; i < usings.Count; i++)
                sb.AppendLine(usings[i]);

            if (usings.Count > 0)
                sb.AppendLine();

            sb.AppendLine("namespace Playserv.Wrapper");
            sb.AppendLine("{");

            if (state.HasPlayServFacade)
                AppendPlayServFacade(sb, state);

            if (state.HasLocalExecution)
                AppendLocalExecutionDispatch(sb, state);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static List<string> BuildCompatibilityUsings(PlayServGeneratedModuleState state)
        {
            var usings = new List<string>();
            if (state.HasPlayServFacade || state.HasLocalExecution)
                usings.Add("using System;");

            if (state.Data || state.ClientRpc)
                usings.Add("using System.Collections.Generic;");

            if (state.ClientRpc)
                usings.Add("using System.Linq.Expressions;");

            if (state.Data || state.Events || state.Spawn || state.HasPlayServFacade)
                usings.Add("using System.Threading;");

            if (state.Data || state.Events || state.Spawn || state.HasPlayServFacade)
                usings.Add("using System.Threading.Tasks;");

            if (state.Data)
            {
                usings.Add("using Playserv.DataSubscription;");
                usings.Add("using Playserv.DataSubscription.Responses;");
            }

            if (state.ClientRpc || state.Server)
            {
                usings.Add("using Playserv.RPC;");
            }

            if (state.HasLocalExecution)
            {
                usings.Add("using Playserv.Proxy.Common;");
            }

            if (state.Server)
            {
                usings.Add("using Playserv.Server;");
            }

            if (state.HasPlayServFacade)
                usings.Add("using UnityEngine;");

            return usings;
        }

        private static void AppendPlayServFacade(StringBuilder sb, PlayServGeneratedModuleState state)
        {
            sb.AppendLine("    public static partial class PlayServ");
            sb.AppendLine("    {");

            if (state.Data)
                AppendDataFacade(sb);

            if (state.Events)
                AppendEventsFacade(sb);

            if (state.ClientRpc)
                AppendClientRpcFacade(sb);

            if (state.Server)
            {
                AppendServerLocalFacade(sb);
                AppendServerRpcFacade(sb);
            }

            AppendSpawnFacade(sb);

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void AppendDataFacade(StringBuilder sb)
        {
            sb.AppendLine("        public static Task<ISharedEntity<TDto>> SelectEntity<TEntity, TDto>(");
            sb.AppendLine("            string playerId,");
            sb.AppendLine("            Func<TEntity, TDto> map,");
            sb.AppendLine("            DataSubscriptionMode mode = DataSubscriptionMode.Polling)");
            sb.AppendLine("            where TEntity : class");
            sb.AppendLine("            where TDto : class, new() =>");
            sb.AppendLine("            PlayServData.SelectEntity<TEntity, TDto>(playerId, map, mode);");
            sb.AppendLine();
            sb.AppendLine("        public static Task<DataGetResponse> GetDataByKeyAsync(");
            sb.AppendLine("            string key,");
            sb.AppendLine("            string query,");
            sb.AppendLine("            Dictionary<string, object> variables,");
            sb.AppendLine("            CancellationToken ct = default) =>");
            sb.AppendLine("            PlayServData.GetDataByKeyAsync(key, query, variables, ct);");
            sb.AppendLine();
            sb.AppendLine("        public static IDisposable StartDataByKeyPolling(");
            sb.AppendLine("            string key,");
            sb.AppendLine("            string query,");
            sb.AppendLine("            Dictionary<string, object> variables,");
            sb.AppendLine("            Action<DataGetResponse> onData,");
            sb.AppendLine("            Action<Exception> onError = null) =>");
            sb.AppendLine("            PlayServData.StartDataByKeyPolling(key, query, variables, onData, onError);");
            sb.AppendLine();
        }

        private static void AppendEventsFacade(StringBuilder sb)
        {
            sb.AppendLine("        public static IObservable<T> Subscribe<T>() =>");
            sb.AppendLine("            PlayServEvents.Subscribe<T>();");
            sb.AppendLine();
            sb.AppendLine("        public static IDisposable Subscribe<T>(Action<T> onNext) =>");
            sb.AppendLine("            PlayServEvents.Subscribe(onNext);");
            sb.AppendLine();
            sb.AppendLine("        public static void Publish<T>(T @event) =>");
            sb.AppendLine("            PlayServEvents.Publish(@event);");
            sb.AppendLine();
            sb.AppendLine("        public static void PublishForGroup<T>(string groupName, T @event) =>");
            sb.AppendLine("            PlayServEvents.PublishForGroup(groupName, @event);");
            sb.AppendLine();
            sb.AppendLine("        public static void PublishForUser<T>(string userId, T @event) =>");
            sb.AppendLine("            PlayServEvents.PublishForUser(userId, @event);");
            sb.AppendLine();
            sb.AppendLine("        public static Task<bool> SubscribeGroupAsync(string groupName, CancellationToken ct = default) =>");
            sb.AppendLine("            PlayServEvents.SubscribeGroupAsync(groupName, ct);");
            sb.AppendLine();
            sb.AppendLine("        public static Task<bool> UnsubscribeGroupAsync(string groupName, CancellationToken ct = default) =>");
            sb.AppendLine("            PlayServEvents.UnsubscribeGroupAsync(groupName, ct);");
            sb.AppendLine();
        }

        private static void AppendClientRpcFacade(StringBuilder sb)
        {
            sb.AppendLine("        public static event Action<InvokeRpcResponse> OnRpcInvokeResponse");
            sb.AppendLine("        {");
            sb.AppendLine("            add => PlayServRpc.OnRpcInvokeResponse += value;");
            sb.AppendLine("            remove => PlayServRpc.OnRpcInvokeResponse -= value;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void Send<T>(T command) =>");
            sb.AppendLine("            PlayServRpc.Send(command);");
            sb.AppendLine();
            sb.AppendLine("        public static void Send<T>(T command, string moduleName) =>");
            sb.AppendLine("            PlayServRpc.Send(command, moduleName);");
            sb.AppendLine();

            sb.AppendLine("        public static void Invoke(string serviceName, string methodName, object payload) =>");
            sb.AppendLine("            PlayServRpc.Invoke(serviceName, methodName, payload);");
            sb.AppendLine();
            sb.AppendLine("        public static void InvokeArgs(string serviceName, string methodName, params object[] args) =>");
            sb.AppendLine("            PlayServRpc.InvokeArgs(serviceName, methodName, args);");
            sb.AppendLine();
            sb.AppendLine("        public static void InvokeNamed(string serviceName, string methodName, IDictionary<string, object> payload) =>");
            sb.AppendLine("            PlayServRpc.InvokeNamed(serviceName, methodName, payload);");
            sb.AppendLine();
            sb.AppendLine("        public static void Invoke(string serviceName, string methodName, string payloadBase64) =>");
            sb.AppendLine("            PlayServRpc.Invoke(serviceName, methodName, payloadBase64);");
            sb.AppendLine();
            sb.AppendLine("        public static void Invoke<TService>(Expression<Action<TService>> method) =>");
            sb.AppendLine("            PlayServRpc.Invoke(method);");
            sb.AppendLine();
            sb.AppendLine("        public static void Invoke<TService>(Expression<Action<TService>> method, object payload) =>");
            sb.AppendLine("            PlayServRpc.Invoke(method, payload);");
            sb.AppendLine();
            sb.AppendLine("        public static void Invoke<TService>(Expression<Action<TService>> method, string payloadBase64) =>");
            sb.AppendLine("            PlayServRpc.Invoke(method, payloadBase64);");
            sb.AppendLine();
        }

        private static void AppendServerLocalFacade(StringBuilder sb)
        {
            sb.AppendLine("        public static void SetCommandHandler(ICommandHandler commandHandler)");
            sb.AppendLine("        {");
            sb.AppendLine("            var configurator = Playserv.Proxy.Common.PlayServRuntimeHost.LocalExecution as ILocalCommandExecutionConfigurator;");
            sb.AppendLine("            if (configurator == null)");
            sb.AppendLine("                throw new InvalidOperationException(\"Server module is not installed or enabled.\");");
            sb.AppendLine();
            sb.AppendLine("            configurator.SetCommandHandler(commandHandler);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void SetEventHandler(IEventHandler eventHandler)");
            sb.AppendLine("        {");
            sb.AppendLine("            var configurator = Playserv.Proxy.Common.PlayServRuntimeHost.LocalExecution as ILocalEventExecutionConfigurator;");
            sb.AppendLine("            if (configurator == null)");
            sb.AppendLine("                throw new InvalidOperationException(\"Server module is not installed or enabled.\");");
            sb.AppendLine();
            sb.AppendLine("            configurator.SetEventHandler(eventHandler);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendServerRpcFacade(StringBuilder sb)
        {
            sb.AppendLine("        public static void SetRpcInvoker(IRpcInvoker rpcInvoker) =>");
            sb.AppendLine("            PlayServServerRpc.SetRpcInvoker(rpcInvoker);");
            sb.AppendLine();
        }

        private static void AppendSpawnFacade(StringBuilder sb)
        {
            sb.AppendLine("        public static Task<GameObject> Spawn(string assetName, Vector3 position, Quaternion rotation) =>");
            sb.AppendLine("            InvokeSpawnGameObject(nameof(Spawn), new[] { typeof(string), typeof(Vector3), typeof(Quaternion) }, assetName, position, rotation);");
            sb.AppendLine();
            sb.AppendLine("        public static Task<GameObject> Spawn(string assetName, Vector3 position) =>");
            sb.AppendLine("            InvokeSpawnGameObject(nameof(Spawn), new[] { typeof(string), typeof(Vector3) }, assetName, position);");
            sb.AppendLine();
            sb.AppendLine("        public static string CurrentSpawnScope => InvokeSpawnStringProperty(\"CurrentScope\");");
            sb.AppendLine();
            sb.AppendLine("        public static Task<bool> JoinSpawnScopeAsync(string groupName, CancellationToken ct = default) =>");
            sb.AppendLine("            InvokeSpawnBoolTask(nameof(JoinSpawnScopeAsync), new[] { typeof(string), typeof(CancellationToken) }, groupName, ct);");
            sb.AppendLine();
            sb.AppendLine("        public static Task<bool> JoinSpawnScope(string groupName, CancellationToken ct = default) =>");
            sb.AppendLine("            InvokeSpawnBoolTask(nameof(JoinSpawnScope), new[] { typeof(string), typeof(CancellationToken) }, groupName, ct);");
            sb.AppendLine();
            sb.AppendLine("        public static Task<bool> LeaveSpawnScopeAsync(CancellationToken ct = default) =>");
            sb.AppendLine("            InvokeSpawnBoolTask(nameof(LeaveSpawnScopeAsync), new[] { typeof(CancellationToken) }, ct);");
            sb.AppendLine();
            sb.AppendLine("        public static Task<bool> LeaveSpawnScope(CancellationToken ct = default) =>");
            sb.AppendLine("            InvokeSpawnBoolTask(nameof(LeaveSpawnScope), new[] { typeof(CancellationToken) }, ct);");
            sb.AppendLine();
            sb.AppendLine("        public static bool Despawn(string spawnId) =>");
            sb.AppendLine("            InvokeSpawnBool(nameof(Despawn), new[] { typeof(string) }, spawnId);");
            sb.AppendLine();
            sb.AppendLine("        public static bool Despawn(GameObject instance) =>");
            sb.AppendLine("            InvokeSpawnBool(nameof(Despawn), new[] { typeof(GameObject) }, instance);");
            sb.AppendLine();
            sb.AppendLine("        private const string SpawnFacadeTypeName = \"Playserv.Wrapper.PlayServSpawn, Playserv.Runtime.Modules.Spawn\";");
            sb.AppendLine();
            sb.AppendLine("        private static Task<GameObject> InvokeSpawnGameObject(string methodName, Type[] parameterTypes, params object[] args)");
            sb.AppendLine("        {");
            sb.AppendLine("            return InvokeSpawn<Task<GameObject>>(methodName, parameterTypes, args) ?? FaultedSpawnTask<GameObject>(SpawnModuleUnavailableException());");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static Task<bool> InvokeSpawnBoolTask(string methodName, Type[] parameterTypes, params object[] args)");
            sb.AppendLine("        {");
            sb.AppendLine("            return InvokeSpawn<Task<bool>>(methodName, parameterTypes, args) ?? FaultedSpawnTask<bool>(SpawnModuleUnavailableException());");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static bool InvokeSpawnBool(string methodName, Type[] parameterTypes, params object[] args)");
            sb.AppendLine("        {");
            sb.AppendLine("            return InvokeSpawn<bool>(methodName, parameterTypes, args);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string InvokeSpawnStringProperty(string propertyName)");
            sb.AppendLine("        {");
            sb.AppendLine("            var type = Type.GetType(SpawnFacadeTypeName, throwOnError: false);");
            sb.AppendLine("            var property = type?.GetProperty(propertyName);");
            sb.AppendLine("            return property?.GetValue(null, null) as string ?? string.Empty;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static T InvokeSpawn<T>(string methodName, Type[] parameterTypes, params object[] args)");
            sb.AppendLine("        {");
            sb.AppendLine("            var type = Type.GetType(SpawnFacadeTypeName, throwOnError: false);");
            sb.AppendLine("            var method = type?.GetMethod(methodName, parameterTypes);");
            sb.AppendLine("            if (method == null)");
            sb.AppendLine("                return default;");
            sb.AppendLine();
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                return (T)method.Invoke(null, args);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (typeof(T) == typeof(Task<GameObject>))");
            sb.AppendLine("                    return (T)(object)FaultedSpawnTask<GameObject>(ex.InnerException ?? ex);");
            sb.AppendLine();
            sb.AppendLine("                if (typeof(T) == typeof(Task<bool>))");
            sb.AppendLine("                    return (T)(object)FaultedSpawnTask<bool>(ex.InnerException ?? ex);");
            sb.AppendLine();
            sb.AppendLine("                return default;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static Task<T> FaultedSpawnTask<T>(Exception exception)");
            sb.AppendLine("        {");
            sb.AppendLine("            var tcs = new TaskCompletionSource<T>();");
            sb.AppendLine("            tcs.SetException(exception);");
            sb.AppendLine("            return tcs.Task;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static InvalidOperationException SpawnModuleUnavailableException() =>");
            sb.AppendLine("            new InvalidOperationException(\"PlayServ Spawn module is not installed or enabled.\");");
            sb.AppendLine();
        }

        private static void AppendLocalExecutionDispatch(StringBuilder sb, PlayServGeneratedModuleState state)
        {
            sb.AppendLine("    internal static partial class PlayServCommandDispatchFactory");
            sb.AppendLine("    {");
            sb.AppendLine("        static partial void TryCreateModuleDispatch(ref IPlayServCommandDispatch dispatch)");
            sb.AppendLine("        {");
            sb.AppendLine("            var localExecution = CreateLocalExecution();");
            sb.AppendLine("            if (localExecution != null)");
            sb.AppendLine("                dispatch = new PlayServLocalExecutionCommandDispatch(localExecution);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static ILocalCommandExecution CreateLocalExecution()");
            sb.AppendLine("        {");
            if (state.Server)
                sb.AppendLine("            return new PlayServServerLocalExecution();");
            else if (state.ClientExecution)
                sb.AppendLine("            return new NoOpPlayServLocalExecution();");
            else
                sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal sealed class PlayServLocalExecutionCommandDispatch : IPlayServCommandDispatch");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly ILocalCommandExecution _localExecution;");
            sb.AppendLine();
            sb.AppendLine("        public PlayServLocalExecutionCommandDispatch(ILocalCommandExecution localExecution)");
            sb.AppendLine("        {");
            sb.AppendLine("            _localExecution = localExecution ?? throw new ArgumentNullException(nameof(localExecution));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public object LocalExecution => _localExecution;");
            sb.AppendLine();
            sb.AppendLine("        public bool TryHandleCommand<T>(T command, string moduleName, bool hasRuntimeInstance)");
            sb.AppendLine("        {");
            sb.AppendLine("            return _localExecution.TryHandleCommand(command, moduleName, hasRuntimeInstance);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static string GenerateModuleRegistry(PlayServGeneratedModuleState state)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");

            if (state.Data)
            {
                sb.AppendLine("using Playserv.DataSubscription;");
            }

            if (state.Events)
            {
                sb.AppendLine("using Playserv.Events;");
            }

            sb.AppendLine("using Playserv.Modules;");

            if (state.Pulse)
            {
                sb.AppendLine("using Playserv.Pulse;");
            }

            if (state.RpcCore || state.ClientRpc)
            {
                sb.AppendLine("using Playserv.RPC;");
            }

            if (state.Server)
            {
                sb.AppendLine("using Playserv.Server;");
            }

            if (state.Spawn)
            {
                sb.AppendLine($"#if {SpawnCompileGuard}");
                sb.AppendLine("using Playserv.Spawn;");
                sb.AppendLine("#endif");
            }

            sb.AppendLine();
            sb.AppendLine("namespace Playserv.Modules");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class PlayServModuleRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        static partial void RegisterGenerated(PlayServModuleHost host)");
            sb.AppendLine("        {");

            if (state.Events)
            {
                sb.AppendLine("            RegisterManifestModule(host, PlayServModuleManifest.EventsId, () => new PlayServEventsModule());");
            }

            if (state.Data)
            {
                sb.AppendLine("            RegisterManifestModule(host, PlayServModuleManifest.DataSubscriptionId, () => new PlayServDataSubscriptionModule());");
            }

            if (state.RpcCore)
            {
                sb.AppendLine("            RegisterManifestModule(host, PlayServModuleManifest.RpcCoreId, () => new PlayServRpcCoreModule());");
            }

            if (state.ClientRpc)
            {
                sb.AppendLine("            RegisterManifestModule(host, PlayServModuleManifest.ClientRpcId, () => new PlayServClientRpcModule());");
            }

            if (state.Server)
            {
                sb.AppendLine("            RegisterManifestModule(host, PlayServModuleManifest.ServerId, () => new PlayServServerModule());");
            }

            if (state.Pulse)
            {
                sb.AppendLine("            RegisterManifestModule(host, PlayServModuleManifest.PulseId, () => new PlayServPulseModule());");
            }

            if (state.Spawn)
            {
                sb.AppendLine($"#if {SpawnCompileGuard}");
                sb.AppendLine("            RegisterManifestModule(host, PlayServModuleManifest.SpawnId, () => new PlayServSpawnModule());");
                sb.AppendLine("#endif");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static void RegisterManifestModule(");
            sb.AppendLine("            PlayServModuleHost host,");
            sb.AppendLine("            string moduleId,");
            sb.AppendLine("            Func<IPlayServModule> factory)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!PlayServModuleManifest.TryGet(moduleId, out _))");
            sb.AppendLine("                throw new InvalidOperationException($\"Generated module registry references unknown module id: {moduleId}\");");
            sb.AppendLine();
            sb.AppendLine("            host.Register(factory());");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static bool WriteIfChanged(string relativePath, string contents)
        {
            var path = Path.Combine(PackageRootPath, relativePath);
            return WriteAbsolutePathIfChanged(path, contents);
        }

        private static bool WriteAssetPathIfChanged(string assetPath, string contents)
        {
            var path = ToAbsoluteAssetPath(assetPath);
            return WriteAbsolutePathIfChanged(path, contents);
        }

        private static bool WriteAbsolutePathIfChanged(string path, string contents)
        {
            var directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            contents = NormalizeLineEndings(contents);
            if (File.Exists(path) && NormalizeLineEndings(File.ReadAllText(path)) == contents)
                return false;

            File.WriteAllText(path, contents);
            AssetDatabase.ImportAsset(ToAssetPath(path), ImportAssetOptions.ForceUpdate);
            return true;
        }

        private static string NormalizeLineEndings(string value)
        {
            return (value ?? string.Empty).Replace("\r\n", "\n").Replace("\r", "\n");
        }

        private static string PackageRootPath =>
            _packageRootPath ?? (_packageRootPath = ResolvePackageRootPath());

        private static string ResolvePackageRootPath()
        {
            var guids = AssetDatabase.FindAssets($"{nameof(PlayServGeneratedCompatibilityLayer)} t:MonoScript");
            for (var i = 0; i < guids.Length; i++)
            {
                var assetPath = AssetDatabase.GUIDToAssetPath(guids[i]).Replace('\\', '/');
                if (!assetPath.EndsWith(ThisScriptSuffix, StringComparison.OrdinalIgnoreCase))
                    continue;

                var rootAssetPath = assetPath.Substring(0, assetPath.Length - ThisScriptSuffix.Length);
                return ToAbsoluteAssetPath(rootAssetPath);
            }

            return Path.Combine(Application.dataPath, PackageFolderName);
        }

        private static string ToAbsoluteAssetPath(string assetPath)
        {
            var projectRoot = Directory.GetParent(Application.dataPath)?.FullName ?? Application.dataPath;
            return Path.GetFullPath(Path.Combine(projectRoot, assetPath));
        }

        private static string ToAssetPath(string absolutePath)
        {
            var projectRoot = Directory.GetParent(Application.dataPath)?.FullName ?? Application.dataPath;
            var root = Path.GetFullPath(projectRoot).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            var fullPath = Path.GetFullPath(absolutePath);
            var relative = fullPath.StartsWith(root, StringComparison.OrdinalIgnoreCase)
                ? fullPath.Substring(root.Length).TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                : absolutePath;
            return relative.Replace('\\', '/');
        }

        private readonly struct PlayServGeneratedModuleState
        {
            public PlayServGeneratedModuleState(
                bool events,
                bool data,
                bool rpcCore,
                bool clientRpc,
                bool server,
                bool clientExecution,
                bool spawn,
                bool pulse)
            {
                Events = events;
                Data = data;
                RpcCore = rpcCore;
                ClientRpc = clientRpc;
                Server = server;
                ClientExecution = clientExecution;
                Spawn = spawn;
                Pulse = pulse;
            }

            public bool Events { get; }
            public bool Data { get; }
            public bool RpcCore { get; }
            public bool ClientRpc { get; }
            public bool Server { get; }
            public bool ClientExecution { get; }
            public bool Spawn { get; }
            public bool Pulse { get; }
            public bool HasLocalExecution => ClientExecution || Server;
            public bool HasPlayServFacade => true;
        }
    }

    internal sealed class PlayServGeneratedCompatibilityAssetPostprocessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            if (TouchesModuleLayout(importedAssets) ||
                TouchesModuleLayout(deletedAssets) ||
                TouchesModuleLayout(movedAssets) ||
                TouchesModuleLayout(movedFromAssetPaths))
            {
                PlayServGeneratedCompatibilityLayer.SyncNow();
            }
        }

        private static bool TouchesModuleLayout(string[] paths)
        {
            if (paths == null)
                return false;

            for (var i = 0; i < paths.Length; i++)
            {
                var path = (paths[i] ?? string.Empty).Replace('\\', '/');
                if (path.IndexOf("playserv-unity-sdk/Runtime/Modules/", StringComparison.OrdinalIgnoreCase) >= 0 ||
                    path.IndexOf("playserv-unity-sdk/Editor/Events/", StringComparison.OrdinalIgnoreCase) >= 0 ||
                    path.IndexOf("playserv-unity-sdk/Editor/ModelGenerator/", StringComparison.OrdinalIgnoreCase) >= 0 ||
                    path.IndexOf("playserv-unity-sdk/Editor/CodeGenerator/", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return true;
                }
            }

            return false;
        }
    }
}
