using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PlayServ.Schema.Tool;

internal static class CSharpSchemaAnalyzer
{
    public static AnalysisSnapshot Analyze(
        string projectRoot,
        SchemaToolConfiguration configuration)
    {
        var files = ProjectConfiguration.EnumerateSourceFiles(projectRoot, configuration);
        var contracts = new List<SchemaContract>();
        var diagnostics = new List<SchemaDiagnostic>();

        foreach (var file in files)
        {
            AnalyzeFile(projectRoot, configuration, file, contracts, diagnostics);
        }

        foreach (var duplicate in contracts
                     .GroupBy(contract => contract.Id, StringComparer.Ordinal)
                     .Where(group => group.Count() > 1))
        {
            foreach (var contract in duplicate)
            {
                diagnostics.Add(new SchemaDiagnostic
                {
                    Severity = "error",
                    Code = "PSSCHEMA001",
                    Message = $"Duplicate schema id '{duplicate.Key}'.",
                    Path = contract.SourcePath,
                    Line = contract.SourceLine
                });
            }
        }

        foreach (var remoteSource in configuration.Sources.Where(source =>
                     string.Equals(source.Kind, "remote", StringComparison.OrdinalIgnoreCase)))
        {
            diagnostics.Add(new SchemaDiagnostic
            {
                Severity = "info",
                Code = "PSSCHEMA100",
                Message =
                    $"Remote source '{remoteSource.Id}' is configured. Service synchronization " +
                    "will activate when the Schema Service protocol is configured."
            });
        }

        return new AnalysisSnapshot
        {
            SourceFiles = files
                .Select(file => NormalizePath(Path.GetRelativePath(projectRoot, file)))
                .ToArray(),
            Contracts = contracts
                .OrderBy(contract => contract.Id, StringComparer.Ordinal)
                .ToArray(),
            Diagnostics = diagnostics
                .OrderBy(diagnostic => SeverityOrder(diagnostic.Severity))
                .ThenBy(diagnostic => diagnostic.Path, StringComparer.Ordinal)
                .ThenBy(diagnostic => diagnostic.Line)
                .ThenBy(diagnostic => diagnostic.Code, StringComparer.Ordinal)
                .ToArray()
        };
    }

    private static void AnalyzeFile(
        string projectRoot,
        SchemaToolConfiguration configuration,
        string file,
        ICollection<SchemaContract> contracts,
        ICollection<SchemaDiagnostic> diagnostics)
    {
        var text = File.ReadAllText(file);
        if (text.AsSpan(0, Math.Min(text.Length, 256))
            .IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            return;
        }

        var tree = CSharpSyntaxTree.ParseText(
            text,
            new CSharpParseOptions(LanguageVersion.Latest),
            file);
        foreach (var diagnostic in tree.GetDiagnostics().Where(diagnostic =>
                     diagnostic.Severity == DiagnosticSeverity.Error))
        {
            var line = diagnostic.Location.GetLineSpan().StartLinePosition.Line + 1;
            diagnostics.Add(new SchemaDiagnostic
            {
                Severity = "error",
                Code = "PSSCHEMA002",
                Message = diagnostic.GetMessage(),
                Path = NormalizePath(Path.GetRelativePath(projectRoot, file)),
                Line = line
            });
        }

        var root = tree.GetCompilationUnitRoot();
        var relativePath = NormalizePath(Path.GetRelativePath(projectRoot, file));
        var sourceId = ProjectConfiguration.ResolveSourceId(projectRoot, configuration, file);
        var sourceAuthority = ProjectConfiguration.ResolveAuthority(configuration, sourceId);

        foreach (var declaration in root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>())
        {
            var schemaAttribute = FindAttribute(declaration.AttributeLists, "PlayServSchema");
            if (schemaAttribute == null)
                continue;

            var namespaceName = ResolveNamespace(declaration);
            var containingTypes = declaration.Ancestors()
                .OfType<BaseTypeDeclarationSyntax>()
                .Reverse()
                .Select(type => type.Identifier.ValueText);
            var qualifiedNameParts = new List<string>();
            if (!string.IsNullOrWhiteSpace(namespaceName))
                qualifiedNameParts.Add(namespaceName);
            qualifiedNameParts.AddRange(containingTypes);
            qualifiedNameParts.Add(declaration.Identifier.ValueText);
            var fullName = string.Join(".", qualifiedNameParts);
            var id = ReadPositionalString(schemaAttribute, 0);
            if (string.IsNullOrWhiteSpace(id))
                id = fullName;

            var authority = ReadNamedValue(schemaAttribute, "Authority");
            if (string.IsNullOrWhiteSpace(authority))
                authority = sourceAuthority;
            authority = NormalizeEnumValue(authority).ToLowerInvariant();

            var version = ReadNamedString(schemaAttribute, "Version");
            var line = declaration.GetLocation().GetLineSpan().StartLinePosition.Line + 1;
            var formerNames = ReadFormerNames(declaration.AttributeLists);

            if (declaration is EnumDeclarationSyntax enumDeclaration)
            {
                contracts.Add(new SchemaContract
                {
                    Id = id.Trim(),
                    Name = declaration.Identifier.ValueText,
                    FullName = fullName,
                    Kind = "enum",
                    Authority = authority,
                    Version = version,
                    SourceId = sourceId,
                    SourcePath = relativePath,
                    SourceLine = line,
                    FormerNames = formerNames,
                    EnumValues = enumDeclaration.Members
                        .Select(member => member.Identifier.ValueText)
                        .ToArray()
                });
                continue;
            }

            var members = ReadMembers(declaration, relativePath, diagnostics);
            contracts.Add(new SchemaContract
            {
                Id = id.Trim(),
                Name = declaration.Identifier.ValueText,
                FullName = fullName,
                Kind = declaration is StructDeclarationSyntax ? "struct" : "object",
                Authority = authority,
                Version = version,
                SourceId = sourceId,
                SourcePath = relativePath,
                SourceLine = line,
                FormerNames = formerNames,
                Members = members
            });
        }
    }

    private static IReadOnlyList<SchemaMember> ReadMembers(
        BaseTypeDeclarationSyntax declaration,
        string path,
        ICollection<SchemaDiagnostic> diagnostics)
    {
        var members = new List<SchemaMember>();
        if (declaration is RecordDeclarationSyntax record && record.ParameterList != null)
        {
            foreach (var parameter in record.ParameterList.Parameters)
            {
                if (parameter.Type == null ||
                    FindAttribute(parameter.AttributeLists, "PlayServIgnore") != null)
                {
                    continue;
                }

                members.Add(CreateMember(
                    parameter.Identifier.ValueText,
                    parameter.Type,
                    parameter.AttributeLists));
            }
        }

        if (declaration is not TypeDeclarationSyntax typeDeclaration)
            return members;

        foreach (var property in typeDeclaration.Members.OfType<PropertyDeclarationSyntax>())
        {
            if (!HasModifier(property.Modifiers, SyntaxKind.PublicKeyword) ||
                HasModifier(property.Modifiers, SyntaxKind.StaticKeyword) ||
                FindAttribute(property.AttributeLists, "PlayServIgnore") != null)
            {
                continue;
            }

            members.Add(CreateMember(
                property.Identifier.ValueText,
                property.Type,
                property.AttributeLists));
        }

        foreach (var field in typeDeclaration.Members.OfType<FieldDeclarationSyntax>())
        {
            if (!HasModifier(field.Modifiers, SyntaxKind.PublicKeyword) ||
                HasModifier(field.Modifiers, SyntaxKind.StaticKeyword) ||
                HasModifier(field.Modifiers, SyntaxKind.ConstKeyword) ||
                FindAttribute(field.AttributeLists, "PlayServIgnore") != null)
            {
                continue;
            }

            foreach (var variable in field.Declaration.Variables)
            {
                members.Add(CreateMember(
                    variable.Identifier.ValueText,
                    field.Declaration.Type,
                    field.AttributeLists));
            }
        }

        foreach (var duplicate in members
                     .GroupBy(member => member.Name, StringComparer.Ordinal)
                     .Where(group => group.Count() > 1))
        {
            diagnostics.Add(new SchemaDiagnostic
            {
                Severity = "error",
                Code = "PSSCHEMA003",
                Message =
                    $"Type '{declaration.Identifier.ValueText}' contains duplicate schema field " +
                    $"'{duplicate.Key}'.",
                Path = path,
                Line = declaration.GetLocation().GetLineSpan().StartLinePosition.Line + 1
            });
        }

        return members
            .OrderBy(member => member.Name, StringComparer.Ordinal)
            .ToArray();
    }

    private static SchemaMember CreateMember(
        string sourceName,
        TypeSyntax type,
        SyntaxList<AttributeListSyntax> attributes)
    {
        var fieldAttribute = FindAttribute(attributes, "PlayServField");
        var name = fieldAttribute == null
            ? sourceName
            : ReadPositionalString(fieldAttribute, 0);
        if (string.IsNullOrWhiteSpace(name))
            name = sourceName;

        var requiredMode = fieldAttribute == null
            ? string.Empty
            : NormalizeEnumValue(ReadNamedValue(fieldAttribute, "Required"));
        var required = requiredMode switch
        {
            "Required" => true,
            "Optional" => false,
            _ => type is not NullableTypeSyntax
        };

        return new SchemaMember
        {
            Name = name.Trim(),
            SourceName = sourceName,
            TypeName = type.WithoutTrivia().ToString(),
            Required = required,
            FormerNames = ReadFormerNames(attributes)
        };
    }

    private static AttributeSyntax? FindAttribute(
        SyntaxList<AttributeListSyntax> lists,
        string expectedName)
    {
        return lists
            .SelectMany(list => list.Attributes)
            .FirstOrDefault(attribute =>
                string.Equals(
                    NormalizeAttributeName(attribute.Name.ToString()),
                    expectedName,
                    StringComparison.Ordinal));
    }

    private static IReadOnlyList<string> ReadFormerNames(
        SyntaxList<AttributeListSyntax> attributes)
    {
        return attributes
            .SelectMany(list => list.Attributes)
            .Where(attribute => string.Equals(
                NormalizeAttributeName(attribute.Name.ToString()),
                "PlayServFormerlyNamed",
                StringComparison.Ordinal))
            .Select(attribute => ReadPositionalString(attribute, 0))
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim())
            .Distinct(StringComparer.Ordinal)
            .OrderBy(value => value, StringComparer.Ordinal)
            .ToArray();
    }

    private static string ReadPositionalString(AttributeSyntax attribute, int index)
    {
        var arguments = attribute.ArgumentList?.Arguments
            .Where(argument => argument.NameEquals == null && argument.NameColon == null)
            .ToArray();
        if (arguments == null || index < 0 || index >= arguments.Length)
            return string.Empty;

        return ReadStringExpression(arguments[index].Expression);
    }

    private static string ReadNamedString(AttributeSyntax attribute, string name)
    {
        var argument = attribute.ArgumentList?.Arguments.FirstOrDefault(candidate =>
            string.Equals(candidate.NameEquals?.Name.Identifier.ValueText, name, StringComparison.Ordinal));
        return argument == null ? string.Empty : ReadStringExpression(argument.Expression);
    }

    private static string ReadNamedValue(AttributeSyntax attribute, string name)
    {
        var argument = attribute.ArgumentList?.Arguments.FirstOrDefault(candidate =>
            string.Equals(candidate.NameEquals?.Name.Identifier.ValueText, name, StringComparison.Ordinal));
        return argument?.Expression.WithoutTrivia().ToString() ?? string.Empty;
    }

    private static string ReadStringExpression(ExpressionSyntax expression)
    {
        return expression is LiteralExpressionSyntax literal &&
               literal.IsKind(SyntaxKind.StringLiteralExpression)
            ? literal.Token.ValueText
            : string.Empty;
    }

    private static string ResolveNamespace(SyntaxNode declaration)
    {
        return string.Join(
            ".",
            declaration.Ancestors()
                .OfType<BaseNamespaceDeclarationSyntax>()
                .Reverse()
                .Select(namespaceDeclaration => namespaceDeclaration.Name.ToString()));
    }

    private static string NormalizeAttributeName(string name)
    {
        var simpleName = name.Split('.').Last();
        return simpleName.EndsWith("Attribute", StringComparison.Ordinal)
            ? simpleName[..^"Attribute".Length]
            : simpleName;
    }

    private static string NormalizeEnumValue(string value)
    {
        return (value ?? string.Empty).Split('.').Last().Trim();
    }

    private static bool HasModifier(
        SyntaxTokenList modifiers,
        SyntaxKind kind)
    {
        return modifiers.Any(token => token.IsKind(kind));
    }

    private static int SeverityOrder(string severity)
    {
        return severity switch
        {
            "error" => 0,
            "warning" => 1,
            _ => 2
        };
    }

    private static string NormalizePath(string path)
    {
        return path.Replace('\\', '/');
    }
}
