#nullable enable
using System;
using System.Collections.Generic;
using System.Text;

namespace Playserv.CodeGenerator.Editor
{
    internal static class DtoEmitter
    {
        public static string EmitDto(
            string ns,
            string dtoName,
            string source,
            string selection,
            string rootTypeExpr,
            string key,
            TypeIndex typeIndex)
        {
            var rootTypeNameRaw = TypeNameUtil.ExtractTypeofName(rootTypeExpr);

            // IMPORTANT: Keep root type resolution consistent with the generated mapper signature.
            // If rootTypeExpr is `typeof(Player)` and multiple `Player` exist, we must resolve to the same one everywhere.
            var rootTypeNameQualified = string.IsNullOrWhiteSpace(rootTypeNameRaw)
                ? ""
                : TypeNameUtil.QualifyTypeIfNeeded(rootTypeNameRaw, typeIndex);

            // TypeIndex typically stores names without the `global::` prefix.
            var rootTypeLookup = StripGlobalPrefix(rootTypeNameQualified);

            var root = string.IsNullOrWhiteSpace(rootTypeLookup) ? null : typeIndex.Find(rootTypeLookup);

            var tree = SelectionParser.Parse(selection);

            var body = new StringBuilder();

            // 1) DTO properties + nested DTO types
            EmitDtoBody(
                sb: body,
                dtoName: dtoName,
                selection: tree,
                rootType: root,
                rootTypeName: rootTypeLookup,
                typeIndex: typeIndex,
                indent: "        ");

            // 2) Mapper method
            body.AppendLine();
            EmitMapperMethod(
                sb: body,
                dtoName: dtoName,
                selection: tree,
                rootType: root,
                rootTypeName: rootTypeLookup,
                typeIndex: typeIndex,
                indent: "        ");

            // Add usings only if mapper exists (we use Linq + List)
            // Note: Unity C# compiler allows file-level usings before namespace.
            return
$@"// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;

namespace {ns}
{{
    // DTO generated from '{Escape(source)}'
    // Key: {Escape(key)}
    // RootType: {Escape(string.IsNullOrWhiteSpace(rootTypeLookup) ? rootTypeExpr : $"typeof({rootTypeLookup})")}
    // Selection: {Escape(selection)}
    public sealed partial class {dtoName}
    {{
{body.ToString().TrimEnd()}
    }}
}}
#nullable restore
";
        }

        private static void EmitDtoBody(
            StringBuilder sb,
            string dtoName,
            List<SelectionParser.SelectionNode> selection,
            TypeInfoModel? rootType,
            string rootTypeName,
            TypeIndex typeIndex,
            string indent)
        {
            foreach (var node in selection)
            {
                // Resolve member name/type from model using node.Name (not alias)
                var memberNameForResolution = node.Name;

                var memberTypeName = TryResolveMemberType(rootType, memberNameForResolution, out var resolvedMemberName);
                var resolvedMemberTypeName = memberTypeName; // may be null

                // DTO property name:
                // - if alias exists -> alias
                // - else -> resolved member name (PascalCase fix)
                var dtoPropName = !string.IsNullOrWhiteSpace(node.Alias) ? node.Alias! : resolvedMemberName;

                // Determine collection:
                bool isCollection = node.IsArray;
                string? elementTypeName = null;

                if (!string.IsNullOrWhiteSpace(resolvedMemberTypeName) &&
                    TypeNameUtil.TryGetCollectionElementType(resolvedMemberTypeName!, out var elem))
                {
                    isCollection = true;
                    elementTypeName = elem;
                }

                // Leaf field
                if (node.Children.Count == 0)
                {
                    var finalType = resolvedMemberTypeName;

                    if (string.IsNullOrWhiteSpace(finalType))
                    {
                        finalType = "object";
                        sb.AppendLine($"{indent}// TODO: Could not resolve type for '{memberNameForResolution}' on '{rootTypeName}'.");
                    }

                    finalType = TypeNameUtil.QualifyTypeIfNeeded(finalType!, typeIndex);
                    var suffix = GetInitSuffixIfNeeded(finalType!, typeIndex);

                    sb.AppendLine($"{indent}public {finalType} {dtoPropName} {{ get; init; }}{suffix}");
                    continue;
                }

                // Nested field: create nested DTO type and property
                var nestedDtoName = $"{dtoName}_{dtoPropName}_Dto";

                if (!isCollection)
                {
                    sb.AppendLine($"{indent}public {nestedDtoName} {dtoPropName} {{ get; init; }} = default!;");
                }
                else
                {
                    // Normalize collections to List<NestedDto>
                    sb.AppendLine($"{indent}public List<{nestedDtoName}> {dtoPropName} {{ get; init; }} = new();");
                }

                // Resolve nested root type for object/element
                TypeInfoModel? nestedRoot = null;
                string nestedRootTypeName = "UnknownType";

                if (!isCollection)
                {
                    nestedRootTypeName = NormalizeTypeName(resolvedMemberTypeName) ?? "UnknownType";
                    if (nestedRootTypeName != "UnknownType")
                        nestedRoot = typeIndex.Find(nestedRootTypeName);
                }
                else
                {
                    if (!string.IsNullOrWhiteSpace(elementTypeName))
                    {
                        nestedRootTypeName = NormalizeTypeName(elementTypeName) ?? "UnknownType";
                        if (nestedRootTypeName != "UnknownType")
                            nestedRoot = typeIndex.Find(nestedRootTypeName);
                    }
                    else
                    {
                        nestedRootTypeName = NormalizeTypeName(resolvedMemberTypeName) ?? "UnknownType";
                        if (nestedRootTypeName != "UnknownType")
                            nestedRoot = typeIndex.Find(nestedRootTypeName);
                    }
                }

                // Emit nested DTO class
                sb.AppendLine($"{indent}public sealed partial class {nestedDtoName}");
                sb.AppendLine($"{indent}{{");

                EmitDtoBody(
                    sb: sb,
                    dtoName: nestedDtoName,
                    selection: node.Children,
                    rootType: nestedRoot,
                    rootTypeName: nestedRootTypeName,
                    typeIndex: typeIndex,
                    indent: indent + "    ");

                sb.AppendLine($"{indent}}}");
                sb.AppendLine();
            }
        }

        private static void EmitMapperMethod(
            StringBuilder sb,
            string dtoName,
            List<SelectionParser.SelectionNode> selection,
            TypeInfoModel? rootType,
            string rootTypeName,
            TypeIndex typeIndex,
            string indent)
        {
            // Qualify root type for signature if possible (Player -> Playserv.Test.Player)
            var rootTypeQualified = TypeNameUtil.QualifyTypeIfNeeded(rootTypeName, typeIndex);

            sb.AppendLine($"{indent}public static {dtoName} From({rootTypeQualified} src)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    if (src == null) throw new ArgumentNullException(nameof(src));");
            sb.AppendLine();
            sb.AppendLine($"{indent}    return new {dtoName}");
            sb.AppendLine($"{indent}    {{");

            for (int i = 0; i < selection.Count; i++)
            {
                var node = selection[i];

                var memberNameForResolution = node.Name;
                var memberTypeName = TryResolveMemberType(rootType, memberNameForResolution, out var resolvedMemberName);
                var dtoPropName = !string.IsNullOrWhiteSpace(node.Alias) ? node.Alias! : resolvedMemberName;

                bool isCollection = node.IsArray;
                string? elementTypeName = null;

                if (!string.IsNullOrWhiteSpace(memberTypeName) &&
                    TypeNameUtil.TryGetCollectionElementType(memberTypeName!, out var elem))
                {
                    isCollection = true;
                    elementTypeName = elem;
                }

                var comma = (i == selection.Count - 1) ? "" : ",";

                // Leaf mapping
                if (node.Children.Count == 0)
                {
                    // Example: playerName (alias) comes from src.Name (resolvedMemberName)
                    sb.AppendLine($"{indent}        {dtoPropName} = src.{resolvedMemberName}{comma}");
                    continue;
                }

                // Nested mapping
                var nestedDtoName = $"{dtoName}_{dtoPropName}_Dto";

                if (!isCollection)
                {
                    // Example: InventoryObj = src.Inventory == null ? default! : new NestedDto { ... }
                    sb.AppendLine($"{indent}        {dtoPropName} = src.{resolvedMemberName} == null ? default! : {EmitNestedCtorInline(nestedDtoName, node.Children, elementVarName: "src." + resolvedMemberName, rootType: ResolveNestedRoot(typeIndex, memberTypeName), typeIndex: typeIndex, indent: indent + "            ")}{comma}");
                }
                else
                {
                    // Example: Inventory = src.Inventory?.Select(x => new NestedDto { ... }).ToList() ?? new List<NestedDto>()
                    var itemVar = "x";
                    var srcExpr = $"src.{resolvedMemberName}";
                    var nestedRoot = ResolveNestedRoot(typeIndex, elementTypeName ?? memberTypeName);

                    sb.AppendLine($"{indent}        {dtoPropName} = {srcExpr} != null");
                    sb.AppendLine($"{indent}            ? {srcExpr}.Select({itemVar} => {EmitNestedCtorInline(nestedDtoName, node.Children, elementVarName: itemVar, rootType: nestedRoot, typeIndex: typeIndex, indent: indent + "                ") }).ToList()");
                    sb.AppendLine($"{indent}            : new List<{nestedDtoName}>(){comma}");
                }
            }

            sb.AppendLine($"{indent}    }};");
            sb.AppendLine($"{indent}}}");
        }

        private static string EmitNestedCtorInline(
            string nestedDtoName,
            List<SelectionParser.SelectionNode> children,
            string elementVarName,
            TypeInfoModel? rootType,
            TypeIndex typeIndex,
            string indent)
        {
            // Returns string like:
            // new NestedDto
            // {
            //     ItemId = x.ItemId,
            //     itemName = x.ItemName,
            // }
            var sb = new StringBuilder();

            sb.AppendLine($"new {nestedDtoName}");
            sb.AppendLine($"{indent.Substring(0, Math.Max(0, indent.Length - 4))}{{");

            for (int i = 0; i < children.Count; i++)
            {
                var node = children[i];

                var memberTypeName = TryResolveMemberType(rootType, node.Name, out var resolvedMemberName);
                var dtoPropName = !string.IsNullOrWhiteSpace(node.Alias) ? node.Alias! : resolvedMemberName;
                var comma = (i == children.Count - 1) ? "" : ",";

                bool isCollection = node.IsArray;
                string? elementTypeName = null;

                if (!string.IsNullOrWhiteSpace(memberTypeName) &&
                    TypeNameUtil.TryGetCollectionElementType(memberTypeName!, out var elem))
                {
                    isCollection = true;
                    elementTypeName = elem;
                }

                if (node.Children.Count == 0)
                {
                    sb.AppendLine($"{indent}{dtoPropName} = {elementVarName}.{resolvedMemberName}{comma}");
                    continue;
                }

                // Nested inside nested
                var deeperNestedDtoName = $"{nestedDtoName}_{dtoPropName}_Dto";

                if (!isCollection)
                {
                    sb.AppendLine($"{indent}{dtoPropName} = {elementVarName}.{resolvedMemberName} == null ? default! : {EmitNestedCtorInline(deeperNestedDtoName, node.Children, elementVarName: elementVarName + "." + resolvedMemberName, rootType: ResolveNestedRoot(typeIndex, memberTypeName), typeIndex: typeIndex, indent: indent + "    ")}{comma}");
                }
                else
                {
                    var itemVar = "y";
                    var srcExpr = $"{elementVarName}.{resolvedMemberName}";
                    var nestedRoot = ResolveNestedRoot(typeIndex, elementTypeName ?? memberTypeName);

                    sb.AppendLine($"{indent}{dtoPropName} = {srcExpr} != null");
                    sb.AppendLine($"{indent}    ? {srcExpr}.Select({itemVar} => {EmitNestedCtorInline(deeperNestedDtoName, node.Children, elementVarName: itemVar, rootType: nestedRoot, typeIndex: typeIndex, indent: indent + "        ")}).ToList()");
                    sb.AppendLine($"{indent}    : new List<{deeperNestedDtoName}>(){comma}");
                }
            }

            sb.AppendLine($"{indent.Substring(0, Math.Max(0, indent.Length - 4))}}}");

            return sb.ToString().TrimEnd();
        }

        private static TypeInfoModel? ResolveNestedRoot(TypeIndex typeIndex, string? typeName)
        {
            if (typeName == null)
                return null;
            
            if (string.IsNullOrWhiteSpace(typeName))
                return null;

            var t = NormalizeTypeName(typeName);
            if (string.IsNullOrWhiteSpace(t) || t == "UnknownType")
                return null;

            return t == null ? null : typeIndex.Find(t);
        }

        private static string? TryResolveMemberType(TypeInfoModel? rootType, string memberName, out string resolvedMemberName)
        {
            resolvedMemberName = memberName;

            if (rootType == null || string.IsNullOrWhiteSpace(memberName))
                return null;
            
            if (rootType.TryResolveMember(memberName, out var realName, out var realType))
            {
                resolvedMemberName = realName;
                return realType;
            }

            // fallback: try PascalCase (id -> Id)
            var pascal = ToPascalCase(memberName);
            if (!pascal.Equals(memberName, StringComparison.Ordinal) &&
                rootType.TryResolveMember(pascal, out realName, out realType))
            {
                resolvedMemberName = realName;
                return realType;
            }

            return null;
        }

        private static string? NormalizeTypeName(string? typeName)
        {
            if (string.IsNullOrWhiteSpace(typeName))
                return null;

            if (typeName == null)
                return null;

            var t = typeName.Trim();

            if (t.EndsWith("?", StringComparison.Ordinal))
                t = t.Substring(0, t.Length - 1);

            if (t.EndsWith("[]", StringComparison.Ordinal))
                t = t.Substring(0, t.Length - 2);

            if (TypeNameUtil.TryGetCollectionElementType(t, out var elem))
                t = elem;

            t = t.Replace(" ", "");

            // If still generic, keep outer part only for lookup (best-effort)
            var lt = t.IndexOf('<');
            if (lt > 0)
                t = t.Substring(0, lt);

            return t;
        }

        private static string ToPascalCase(string s)
        {
            if (string.IsNullOrWhiteSpace(s)) return s;
            if (s.Length == 1) return s.ToUpperInvariant();
            if (char.IsUpper(s[0])) return s;
            return char.ToUpperInvariant(s[0]) + s.Substring(1);
        }

        private static string GetInitSuffixIfNeeded(string resolvedType, TypeIndex typeIndex)
        {
            if (string.IsNullOrWhiteSpace(resolvedType))
                return "";

            if (resolvedType.EndsWith("?", StringComparison.Ordinal))
                return "";

            if (typeIndex.IsEnum(resolvedType))
                return "";

            if (IsKnownValueType(resolvedType))
                return "";

            if (TypeNameUtil.IsKnownCollectionType(resolvedType))
                return " = default!;";

            if (resolvedType == "string")
                return " = default!;";

            if (char.IsUpper(resolvedType[0]))
                return " = default!;";

            return "";
        }

        private static bool IsKnownValueType(string t)
        {
            switch (t)
            {
                case "bool":
                case "byte":
                case "sbyte":
                case "short":
                case "ushort":
                case "int":
                case "uint":
                case "long":
                case "ulong":
                case "float":
                case "double":
                case "decimal":
                case "char":
                case "System.Boolean":
                case "System.Byte":
                case "System.SByte":
                case "System.Int16":
                case "System.UInt16":
                case "System.Int32":
                case "System.UInt32":
                case "System.Int64":
                case "System.UInt64":
                case "System.Single":
                case "System.Double":
                case "System.Decimal":
                case "System.Char":
                    return true;
                default:
                    return false;
            }
        }

        private static string StripGlobalPrefix(string typeName)
        {
            if (string.IsNullOrWhiteSpace(typeName))
                return typeName;

            const string prefix = "global::";
            return typeName.StartsWith(prefix, StringComparison.Ordinal)
                ? typeName.Substring(prefix.Length)
                : typeName;
        }

        private static string Escape(string s) => (s ?? "").Replace("\r", "").Replace("\n", " ");
    }
}
#nullable restore