using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Playserv.Events;
using Playserv.Modules;
using UnityEditor;
using static System.IO.File;

#nullable enable

namespace Playserv.Events.Editor
{
    internal static class EventsCodeGenerator
    {
        internal const string GeneratedEventsDirectoryPath = "Assets/Shared/Generated/Events/";
        private const string ApiExtensionsOutputPath = "Assets/Shared/Generated/Events/PlayServ.EventsApiExtensions.g.cs";
        private const string AdapterExtensionsOutputPath = "Assets/Shared/Generated/Events/EventsAdapterExtensions.g.cs";
        private const int EventTypeGlobal = 1;
        private const int EventTypeGroup = 2;
        private const int EventTypeUser = 4;
        private const int EventTypeAll = EventTypeGlobal | EventTypeGroup | EventTypeUser;
        private const string PackageSamplesAssemblyName = "Playserv.Samples";
        private const string PackageSamplesNamespace = "Playserv.Samples";
        private const string GeneratorVersion = "events-generator-v3";
        private const string GeneratedHashPrefix = "// <playserv-events-generation-hash:";
        private static readonly Encoding Utf8NoBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

        public static void Generate()
        {
            var changed = SyncGeneratedOutputForCurrentState();
            if (changed)
                AssetDatabase.Refresh();
        }

        public static bool SyncGeneratedOutputForCurrentState()
        {
            if (!CanGenerateEvents())
                return GenerateDisabledOutput();

            var eventTypes = TypeCache.GetTypesWithAttribute<EventAttribute>()
                .Where(IsGeneratedOutputEventType)
                .OrderBy(GetStableTypeIdentity, StringComparer.Ordinal)
                .ToArray();
            var changed = false;

            changed |= GenerateApiExtensionsCode(eventTypes);
            changed |= GenerateAdapterExtensionsCode(eventTypes);

            return changed;
        }

        private static bool CanGenerateEvents()
        {
            var state = Playserv.Editor.PlayServRuntimeModuleDefines.Load();
            Playserv.Editor.PlayServEditorModuleAvailability.NormalizeAvailableRuntimeState(state);
            Playserv.Editor.PlayServRuntimeModuleDefines.NormalizeDependencies(state);
            return state.IsEnabled(PlayServModuleManifest.EventsId) &&
                   Playserv.Editor.PlayServEditorModuleAvailability.EditorEvents;
        }

        private static bool IsGeneratedOutputEventType(Type type)
        {
            if (type == null)
                return false;

            var assemblyName = type.Assembly.GetName().Name;
            if (string.Equals(assemblyName, PackageSamplesAssemblyName, StringComparison.Ordinal))
                return false;

            var typeNamespace = type.Namespace ?? string.Empty;
            return !string.Equals(typeNamespace, PackageSamplesNamespace, StringComparison.Ordinal) &&
                   !typeNamespace.StartsWith(PackageSamplesNamespace + ".", StringComparison.Ordinal);
        }

        private static bool GenerateDisabledOutput()
        {
            var changed = false;
            changed |= WriteFile(ApiExtensionsOutputPath, GenerateDisabledApiExtensionsCode());
            changed |= WriteFile(AdapterExtensionsOutputPath, GenerateDisabledAdapterExtensionsCode());
            return changed;
        }

        private static string GenerateDisabledApiExtensionsCode()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace Playserv.Wrapper");
            sb.AppendLine("{");
            sb.AppendLine("    public static class PlayServEventsApiExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");
            return sb.ToString();
        }

        private static string GenerateDisabledAdapterExtensionsCode()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace Playserv.Events");
            sb.AppendLine("{");
            sb.AppendLine("    public static class EventsAdapterExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");
            return sb.ToString();
        }

        private static bool GenerateApiExtensionsCode(IEnumerable<Type> eventTypes)
        {
            var orderedEventTypes = OrderEventTypes(eventTypes).ToArray();
            var methodSuffixMap = BuildMethodSuffixMap(orderedEventTypes);
            var generationHash = ComputeGenerationHash(orderedEventTypes, methodSuffixMap, "api");
            if (IsGeneratedFileCurrent(ApiExtensionsOutputPath, generationHash))
                return false;

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"{GeneratedHashPrefix}{generationHash}>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Playserv.Events;");
            sb.AppendLine("using Playserv.Wrapper;"); // IPlayServEventsApi lives here in your setup
            sb.AppendLine();
            sb.AppendLine("namespace Playserv.Wrapper");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated convenience methods for events based on [Event] types.");
            sb.AppendLine("    /// Extensions on IPlayServEventsApi.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class PlayServEventsApiExtensions");
            sb.AppendLine("    {");

            foreach (var type in orderedEventTypes)
            {
                if (!TryGetEventType(type, out var eventType))
                    continue;

                if ((eventType & EventTypeGlobal) != 0)
                    AppendApiGlobalEventMethods(sb, type, methodSuffixMap[type]);

                if ((eventType & EventTypeGroup) != 0)
                    AppendApiGroupEventMethods(sb, type, methodSuffixMap[type]);

                if ((eventType & EventTypeUser) != 0)
                    AppendApiUserEventMethods(sb, type, methodSuffixMap[type]);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");

            return WriteFile(ApiExtensionsOutputPath, sb.ToString());
        }

        private static bool GenerateAdapterExtensionsCode(IEnumerable<Type> eventTypes)
        {
            var orderedEventTypes = OrderEventTypes(eventTypes).ToArray();
            var methodSuffixMap = BuildMethodSuffixMap(orderedEventTypes);
            var generationHash = ComputeGenerationHash(orderedEventTypes, methodSuffixMap, "adapter");
            if (IsGeneratedFileCurrent(AdapterExtensionsOutputPath, generationHash))
                return false;

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"{GeneratedHashPrefix}{generationHash}>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Playserv.Events;");
            sb.AppendLine("using Playserv.Proxy;"); // IEventsAdapter
            sb.AppendLine();
            sb.AppendLine("namespace Playserv.Events");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated adapter extensions based on [Event] types.");
            sb.AppendLine("    /// Useful if you work with IEventsAdapter directly.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class EventsAdapterExtensions");
            sb.AppendLine("    {");

            foreach (var type in orderedEventTypes)
            {
                if (!TryGetEventType(type, out var eventType))
                    continue;

                if ((eventType & EventTypeGlobal) != 0)
                    AppendAdapterGlobalEventMethods(sb, type, methodSuffixMap[type]);

                if ((eventType & EventTypeGroup) != 0)
                    AppendAdapterGroupEventMethods(sb, type, methodSuffixMap[type]);

                if ((eventType & EventTypeUser) != 0)
                    AppendAdapterUserEventMethods(sb, type, methodSuffixMap[type]);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");

            return WriteFile(AdapterExtensionsOutputPath, sb.ToString());
        }

        private static bool TryGetEventType(Type type, out int eventType)
        {
            eventType = EventTypeAll;
            var attribute = type
                .GetCustomAttributes(typeof(EventAttribute), inherit: false)
                .OfType<EventAttribute>()
                .FirstOrDefault();

            if (attribute == null)
                return false;

            eventType = (int)attribute.Type;
            return true;
        }

        // ----------------------------
        // IPlayServEventsApi extensions
        // ----------------------------

        private static void AppendApiGlobalEventMethods(StringBuilder sb, Type type, string methodSuffix)
        {
            var field = GetSinglePublicInstanceField(type);
            var eventTypeName = GetCSharpTypeName(type);

            if (field != null)
            {
                var paramType = field.FieldType;
                var paramName = ToCamel(field.Name);

                sb.AppendLine($"        public static void Send{methodSuffix}(this IPlayServEventsApi api, {GetCSharpTypeName(paramType)} {paramName})");
                sb.AppendLine("        {");
                sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
                sb.AppendLine($"            var payload = new {eventTypeName}");
                sb.AppendLine("            {");
                sb.AppendLine($"                {field.Name} = {paramName}");
                sb.AppendLine("            };");
                sb.AppendLine("            api.Publish(payload);");
                sb.AppendLine("        }");
                sb.AppendLine();

                sb.AppendLine($"        public static IDisposable On{methodSuffix}(this IPlayServEventsApi api, Action<{GetCSharpTypeName(paramType)}> onReceive)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
                sb.AppendLine("            if (onReceive == null) throw new ArgumentNullException(nameof(onReceive));");
                sb.AppendLine($"            return api.Subscribe<{eventTypeName}>(e => onReceive(e.{field.Name}));");
                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            sb.AppendLine($"        public static void Send{methodSuffix}(this IPlayServEventsApi api, {eventTypeName} payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
            sb.AppendLine("            api.Publish(payload);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine($"        public static IDisposable On{methodSuffix}(this IPlayServEventsApi api, Action<{eventTypeName}> onReceive)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
            sb.AppendLine("            if (onReceive == null) throw new ArgumentNullException(nameof(onReceive));");
            sb.AppendLine($"            return api.Subscribe<{eventTypeName}>(onReceive);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendApiGroupEventMethods(StringBuilder sb, Type type, string methodSuffix)
        {
            var field = GetSinglePublicInstanceField(type);
            var eventTypeName = GetCSharpTypeName(type);

            if (field != null)
            {
                var paramType = field.FieldType;
                var paramName = ToCamel(field.Name);

                sb.AppendLine($"        public static void SendGroup{methodSuffix}(this IPlayServEventsApi api, string groupName, {GetCSharpTypeName(paramType)} {paramName})");
                sb.AppendLine("        {");
                sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
                sb.AppendLine("            if (groupName == null) throw new ArgumentNullException(nameof(groupName));");
                sb.AppendLine($"            var payload = new {eventTypeName}");
                sb.AppendLine("            {");
                sb.AppendLine($"                {field.Name} = {paramName}");
                sb.AppendLine("            };");
                sb.AppendLine("            api.PublishForGroup(groupName, payload);");
                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            sb.AppendLine($"        public static void SendGroup{methodSuffix}(this IPlayServEventsApi api, string groupName, {eventTypeName} payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
            sb.AppendLine("            if (groupName == null) throw new ArgumentNullException(nameof(groupName));");
            sb.AppendLine("            api.PublishForGroup(groupName, payload);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendApiUserEventMethods(StringBuilder sb, Type type, string methodSuffix)
        {
            var field = GetSinglePublicInstanceField(type);
            var eventTypeName = GetCSharpTypeName(type);

            if (field != null)
            {
                var paramType = field.FieldType;
                var paramName = ToCamel(field.Name);

                sb.AppendLine($"        public static void SendUser{methodSuffix}(this IPlayServEventsApi api, string userId, {GetCSharpTypeName(paramType)} {paramName})");
                sb.AppendLine("        {");
                sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
                sb.AppendLine("            if (userId == null) throw new ArgumentNullException(nameof(userId));");
                sb.AppendLine($"            var payload = new {eventTypeName}");
                sb.AppendLine("            {");
                sb.AppendLine($"                {field.Name} = {paramName}");
                sb.AppendLine("            };");
                sb.AppendLine("            api.PublishForUser(userId, payload);");
                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            sb.AppendLine($"        public static void SendUser{methodSuffix}(this IPlayServEventsApi api, string userId, {eventTypeName} payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
            sb.AppendLine("            if (userId == null) throw new ArgumentNullException(nameof(userId));");
            sb.AppendLine("            api.PublishForUser(userId, payload);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ----------------------------
        // IEventsAdapter extensions (optional)
        // ----------------------------

        private static void AppendAdapterGlobalEventMethods(StringBuilder sb, Type type, string methodSuffix)
        {
            var field = GetSinglePublicInstanceField(type);
            var eventTypeName = GetCSharpTypeName(type);

            if (field != null)
            {
                var paramType = field.FieldType;
                var paramName = ToCamel(field.Name);

                sb.AppendLine($"        public static void Publish{methodSuffix}(this IEventsAdapter adapter, {GetCSharpTypeName(paramType)} {paramName})");
                sb.AppendLine("        {");
                sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
                sb.AppendLine($"            var payload = new {eventTypeName}");
                sb.AppendLine("            {");
                sb.AppendLine($"                {field.Name} = {paramName}");
                sb.AppendLine("            };");
                sb.AppendLine("            adapter.Publish(payload);");
                sb.AppendLine("        }");
                sb.AppendLine();

                sb.AppendLine($"        public static IDisposable On{methodSuffix}(this IEventsAdapter adapter, Action<{GetCSharpTypeName(paramType)}> onReceive)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
                sb.AppendLine("            if (onReceive == null) throw new ArgumentNullException(nameof(onReceive));");
                sb.AppendLine($"            return adapter.Subscribe<{eventTypeName}>()");
                sb.AppendLine($"                .Subscribe(e => onReceive(e.{field.Name}));");
                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            sb.AppendLine($"        public static void Publish{methodSuffix}(this IEventsAdapter adapter, {eventTypeName} payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
            sb.AppendLine("            adapter.Publish(payload);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine($"        public static IDisposable On{methodSuffix}(this IEventsAdapter adapter, Action<{eventTypeName}> onReceive)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
            sb.AppendLine("            if (onReceive == null) throw new ArgumentNullException(nameof(onReceive));");
            sb.AppendLine($"            return adapter.Subscribe<{eventTypeName}>()");
            sb.AppendLine("                .Subscribe(onReceive);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendAdapterGroupEventMethods(StringBuilder sb, Type type, string methodSuffix)
        {
            var field = GetSinglePublicInstanceField(type);
            var eventTypeName = GetCSharpTypeName(type);

            if (field != null)
            {
                var paramType = field.FieldType;
                var paramName = ToCamel(field.Name);

                sb.AppendLine($"        public static void PublishGroup{methodSuffix}(this IEventsAdapter adapter, string groupName, {GetCSharpTypeName(paramType)} {paramName})");
                sb.AppendLine("        {");
                sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
                sb.AppendLine($"            var payload = new {eventTypeName}");
                sb.AppendLine("            {");
                sb.AppendLine($"                {field.Name} = {paramName}");
                sb.AppendLine("            };");
                sb.AppendLine("            adapter.PublishForGroup(groupName, payload);");
                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            sb.AppendLine($"        public static void PublishGroup{methodSuffix}(this IEventsAdapter adapter, string groupName, {eventTypeName} payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
            sb.AppendLine("            adapter.PublishForGroup(groupName, payload);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendAdapterUserEventMethods(StringBuilder sb, Type type, string methodSuffix)
        {
            var field = GetSinglePublicInstanceField(type);
            var eventTypeName = GetCSharpTypeName(type);

            if (field != null)
            {
                var paramType = field.FieldType;
                var paramName = ToCamel(field.Name);

                sb.AppendLine($"        public static void PublishUser{methodSuffix}(this IEventsAdapter adapter, string userId, {GetCSharpTypeName(paramType)} {paramName})");
                sb.AppendLine("        {");
                sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
                sb.AppendLine($"            var payload = new {eventTypeName}");
                sb.AppendLine("            {");
                sb.AppendLine($"                {field.Name} = {paramName}");
                sb.AppendLine("            };");
                sb.AppendLine("            adapter.PublishForUser(userId, payload);");
                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            sb.AppendLine($"        public static void PublishUser{methodSuffix}(this IEventsAdapter adapter, string userId, {eventTypeName} payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
            sb.AppendLine("            adapter.PublishForUser(userId, payload);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ----------------------------
        // Helpers
        // ----------------------------

        private static System.Reflection.FieldInfo? GetSinglePublicInstanceField(Type type)
        {
            var fields = type
                .GetFields(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public)
                .Where(f => !f.IsStatic)
                .ToArray();

            if (fields.Length != 1)
                return null;

            return fields[0];
        }

        private static Dictionary<Type, string> BuildMethodSuffixMap(IEnumerable<Type> eventTypes)
        {
            var types = OrderEventTypes(eventTypes)
                .Distinct()
                .ToArray();

            var suffixMap = new Dictionary<Type, string>();

            foreach (var group in types.GroupBy(t => t.Name, StringComparer.Ordinal))
            {
                if (group.Count() == 1)
                {
                    var type = group.First();
                    suffixMap[type] = SanitizeIdentifierPart(type.Name);
                    continue;
                }

                var usedSuffixes = new HashSet<string>(StringComparer.Ordinal);

                foreach (var type in group.OrderBy(t => t.FullName, StringComparer.Ordinal))
                {
                    var suffix = BuildQualifiedMethodSuffix(type);
                    if (!usedSuffixes.Add(suffix))
                    {
                        var fallbackBase = BuildCollisionFallbackMethodSuffix(type);
                        suffix = fallbackBase;

                        var counter = 2;
                        while (!usedSuffixes.Add(suffix))
                        {
                            suffix = $"{fallbackBase}_{counter}";
                            counter++;
                        }
                    }

                    suffixMap[type] = suffix;
                }
            }

            return suffixMap;
        }

        private static IEnumerable<Type> OrderEventTypes(IEnumerable<Type> eventTypes)
        {
            return eventTypes
                .Where(type => type != null)
                .OrderBy(GetStableTypeIdentity, StringComparer.Ordinal);
        }

        private static string GetStableTypeIdentity(Type type)
        {
            var assemblyName = type.Assembly.GetName().Name ?? string.Empty;
            var fullName = type.FullName ?? type.AssemblyQualifiedName ?? type.Name;
            return $"{fullName}|{assemblyName}";
        }

        private static string BuildQualifiedMethodSuffix(Type type)
        {
            var parts = new List<string>();

            if (!string.IsNullOrWhiteSpace(type.Namespace))
            {
                parts.AddRange(type.Namespace
                    .Split('.')
                    .Select(SanitizeIdentifierPart)
                    .Where(part => part.Length > 0));
            }

            foreach (var declaringType in GetDeclaringTypes(type))
                parts.Add(SanitizeIdentifierPart(declaringType.Name));

            parts.Add(SanitizeIdentifierPart(type.Name));

            var suffix = string.Join("_", parts.Where(part => part.Length > 0));
            return string.IsNullOrWhiteSpace(suffix) ? "Event" : suffix;
        }

        private static string BuildCollisionFallbackMethodSuffix(Type type)
        {
            var identity = type.FullName ?? type.AssemblyQualifiedName ?? type.Name;
            var sanitizedIdentity = SanitizeIdentifierPart(identity);
            var hash = ComputeStableHash(identity);
            return $"{sanitizedIdentity}_{hash}";
        }

        private static IEnumerable<Type> GetDeclaringTypes(Type type)
        {
            var declaringTypes = new Stack<Type>();
            var current = type.DeclaringType;

            while (current != null)
            {
                declaringTypes.Push(current);
                current = current.DeclaringType;
            }

            return declaringTypes;
        }

        private static string SanitizeIdentifierPart(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return string.Empty;

            var sb = new StringBuilder(value.Length);
            var previousWasUnderscore = false;

            foreach (var ch in value)
            {
                if (char.IsLetterOrDigit(ch) || ch == '_')
                {
                    sb.Append(ch);
                    previousWasUnderscore = false;
                    continue;
                }

                if (!previousWasUnderscore)
                {
                    sb.Append('_');
                    previousWasUnderscore = true;
                }
            }

            var sanitized = sb.ToString().Trim('_');
            if (string.IsNullOrWhiteSpace(sanitized))
                return string.Empty;

            if (char.IsDigit(sanitized[0]))
                sanitized = "_" + sanitized;

            return sanitized;
        }

        private static string ComputeStableHash(string value)
        {
            unchecked
            {
                var hash = 2166136261u;

                foreach (var ch in value)
                {
                    hash ^= ch;
                    hash *= 16777619u;
                }

                return hash.ToString("x8");
            }
        }

        private static string ComputeGenerationHash(
            IEnumerable<Type> orderedEventTypes,
            IReadOnlyDictionary<Type, string> methodSuffixMap,
            string outputKind)
        {
            var sb = new StringBuilder();
            sb.AppendLine(GeneratorVersion);
            sb.AppendLine(outputKind);

            foreach (var type in orderedEventTypes)
            {
                if (!TryGetEventType(type, out var eventType))
                    continue;

                sb.Append(GetStableTypeIdentity(type));
                sb.Append('|');
                sb.Append(eventType);
                sb.Append('|');
                sb.Append(methodSuffixMap[type]);
                sb.Append('|');
                sb.Append(GetCSharpTypeName(type));

                var field = GetSinglePublicInstanceField(type);
                if (field != null)
                {
                    sb.Append("|field:");
                    sb.Append(field.Name);
                    sb.Append(':');
                    sb.Append(GetStableTypeIdentity(field.FieldType));
                    sb.Append(':');
                    sb.Append(GetCSharpTypeName(field.FieldType));
                }

                sb.AppendLine();
            }

            return ComputeStableHash(sb.ToString());
        }

        private static bool IsGeneratedFileCurrent(string assetPath, string generationHash)
        {
            var fullPath = Path.GetFullPath(assetPath);
            if (!File.Exists(fullPath))
                return false;

            try
            {
                foreach (var line in File.ReadLines(fullPath).Take(4))
                {
                    if (!line.StartsWith(GeneratedHashPrefix, StringComparison.Ordinal))
                        continue;

                    var currentHash = line
                        .Substring(GeneratedHashPrefix.Length)
                        .TrimEnd('>');
                    return string.Equals(currentHash, generationHash, StringComparison.Ordinal);
                }
            }
            catch
            {
                return false;
            }

            return false;
        }

        private static string ToCamel(string s)
        {
            if (string.IsNullOrWhiteSpace(s))
                return s;

            if (s.Length == 1)
                return char.ToLowerInvariant(s[0]).ToString();

            return char.ToLowerInvariant(s[0]) + s.Substring(1);
        }

        private static string GetCSharpTypeName(Type type)
        {
            if (type.IsByRef)
                return GetCSharpElementTypeName(type);

            if (type.IsPointer)
                return $"{GetCSharpElementTypeName(type)}*";

            if (type.IsArray)
            {
                var rankSuffix = type.GetArrayRank() == 1
                    ? string.Empty
                    : new string(',', type.GetArrayRank() - 1);
                return $"{GetCSharpElementTypeName(type)}[{rankSuffix}]";
            }

            if (type.IsGenericParameter)
                return type.Name;

            if (!type.IsGenericType)
                return GetCSharpNonGenericTypeName(type);

            var typeDefName = StripGenericArity(GetCSharpNonGenericTypeName(type.GetGenericTypeDefinition()));

            var genericArgs = type.GetGenericArguments()
                .Select(GetCSharpTypeName)
                .ToArray();

            return $"{typeDefName}<{string.Join(", ", genericArgs)}>";
        }

        private static string GetCSharpElementTypeName(Type type)
        {
            var elementType = type.GetElementType();
            return elementType == null
                ? "global::System.Object"
                : GetCSharpTypeName(elementType);
        }

        private static string GetCSharpNonGenericTypeName(Type type)
        {
            var declaringTypes = GetDeclaringTypes(type).ToArray();
            var rootType = declaringTypes.Length > 0 ? declaringTypes[0] : type;

            var typeParts = declaringTypes
                .Select(declaringType => StripGenericArity(declaringType.Name))
                .Concat(new[] { StripGenericArity(type.Name) })
                .Where(part => !string.IsNullOrWhiteSpace(part));

            var localTypeName = string.Join(".", typeParts);
            if (string.IsNullOrWhiteSpace(rootType.Namespace))
                return $"global::{localTypeName}";

            return $"global::{rootType.Namespace}.{localTypeName}";
        }

        private static string StripGenericArity(string typeName)
        {
            if (string.IsNullOrWhiteSpace(typeName))
                return string.Empty;

            var tickIndex = typeName.IndexOf('`');
            return tickIndex >= 0
                ? typeName.Substring(0, tickIndex)
                : typeName;
        }

        private static bool WriteFile(string assetPath, string content)
        {
            var fullPath = Path.GetFullPath(assetPath);
            var directory = Path.GetDirectoryName(fullPath);
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            if (File.Exists(fullPath))
            {
                var existing = File.ReadAllText(fullPath, Encoding.UTF8);
                if (string.Equals(NormalizeGeneratedContent(existing), NormalizeGeneratedContent(content), StringComparison.Ordinal))
                    return false;
            }

            WriteAllText(fullPath, content, Utf8NoBom);
            return true;
        }

        private static string NormalizeGeneratedContent(string content)
        {
            return (content ?? string.Empty)
                .TrimStart('\uFEFF')
                .Replace("\r\n", "\n")
                .Replace("\r", "\n");
        }
    }
}
#nullable restore
