// Assets/Playserv/Editor/Events/EventsCodeGenerator.cs
#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using static System.IO.File;

#nullable enable

namespace Playserv.Events.Editor
{
    internal static class EventsCodeGenerator
    {
        // NOTE:
        // If generated code can't see Playserv.Runtime assembly (IPlayServEventsApi / events),
        // either:
        // 1) Move output into your Runtime folder (recommended), e.g.:
        //    "Assets/Playserv/Runtime/Generated/PlayServ.EventsApiExtensions.g.cs"
        // or
        // 2) Add an asmdef for Assets/PlayservGenerated and reference Playserv.Runtime.asmdef.
        private const string ApiExtensionsOutputPath = "Assets/Shared/Generated/Events/PlayServ.EventsApiExtensions.g.cs";
        private const string AdapterExtensionsOutputPath = "Assets/Shared/Generated/Events/EventsAdapterExtensions.g.cs";

        [MenuItem("Tools/PlayServ/Generate Events API")]
        public static void Generate()
        {
            var eventTypes = TypeCache.GetTypesWithAttribute<EventAttribute>();

            GenerateApiExtensionsCode(eventTypes);
            GenerateAdapterExtensionsCode(eventTypes); // Optional: keep if you use IEventsAdapter in runtime

            AssetDatabase.Refresh();
        }

        private static void GenerateApiExtensionsCode(TypeCache.TypeCollection eventTypes)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Playserv.Events;");
            sb.AppendLine("using Playserv.Wrapper;"); // IPlayServEventsApi lives here in your setup
            sb.AppendLine();
            sb.AppendLine("namespace Playserv.Wrapper");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated convenience methods for events based on [Event] types.");
            sb.AppendLine("    /// Extensions on IPlayServEventsApi.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class PlayServEventsApiExtensions");
            sb.AppendLine("    {");

            foreach (var type in eventTypes)
            {
                var attribute = type.GetCustomAttribute<EventAttribute>();
                if (attribute == null)
                    continue;

                var eventType = attribute.Type;

                if ((eventType & EventType.Global) != 0)
                    AppendApiGlobalEventMethods(sb, type);

                if ((eventType & EventType.Group) != 0)
                    AppendApiGroupEventMethods(sb, type);

                if ((eventType & EventType.User) != 0)
                    AppendApiUserEventMethods(sb, type);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");

            WriteFile(ApiExtensionsOutputPath, sb.ToString());
        }

        private static void GenerateAdapterExtensionsCode(TypeCache.TypeCollection eventTypes)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Playserv.Events;");
            sb.AppendLine("using Playserv.Proxy;"); // IEventsAdapter
            sb.AppendLine();
            sb.AppendLine("namespace Playserv.Events");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated adapter extensions based on [Event] types.");
            sb.AppendLine("    /// Useful if you work with IEventsAdapter directly.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class EventsAdapterExtensions");
            sb.AppendLine("    {");

            foreach (var type in eventTypes)
            {
                var attribute = type.GetCustomAttribute<EventAttribute>();
                if (attribute == null)
                    continue;

                var eventType = attribute.Type;

                if ((eventType & EventType.Global) != 0)
                    AppendAdapterGlobalEventMethods(sb, type);

                if ((eventType & EventType.Group) != 0)
                    AppendAdapterGroupEventMethods(sb, type);

                if ((eventType & EventType.User) != 0)
                    AppendAdapterUserEventMethods(sb, type);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#nullable restore");

            WriteFile(AdapterExtensionsOutputPath, sb.ToString());
        }

        // ----------------------------
        // IPlayServEventsApi extensions
        // ----------------------------

        private static void AppendApiGlobalEventMethods(StringBuilder sb, Type type)
        {
            var field = GetSinglePublicInstanceField(type);
            if (field == null)
                return;

            var methodSuffix = type.Name;
            var paramType = field.FieldType;
            var paramName = ToCamel(field.Name);
            var fullEventTypeName = $"global::{type.FullName}";

            // SendX(this IPlayServEventsApi api, T value)
            sb.AppendLine($"        public static void Send{methodSuffix}(this IPlayServEventsApi api, {GetFriendlyTypeName(paramType)} {paramName})");
            sb.AppendLine("        {");
            sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
            sb.AppendLine($"            var payload = new {fullEventTypeName}");
            sb.AppendLine("            {");
            sb.AppendLine($"                {field.Name} = {paramName}");
            sb.AppendLine("            };");
            sb.AppendLine("            api.Publish(payload);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // OnX(this IPlayServEventsApi api, Action<T> onReceive)
            sb.AppendLine($"        public static IDisposable On{methodSuffix}(this IPlayServEventsApi api, Action<{GetFriendlyTypeName(paramType)}> onReceive)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
            sb.AppendLine("            if (onReceive == null) throw new ArgumentNullException(nameof(onReceive));");
            sb.AppendLine($"            return api.Subscribe<{fullEventTypeName}>(e => onReceive(e.{field.Name}));");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendApiGroupEventMethods(StringBuilder sb, Type type)
        {
            var field = GetSinglePublicInstanceField(type);
            if (field == null)
                return;

            var methodSuffix = type.Name;
            var paramType = field.FieldType;
            var paramName = ToCamel(field.Name);
            var fullEventTypeName = $"global::{type.FullName}";

            sb.AppendLine($"        public static void SendGroup{methodSuffix}(this IPlayServEventsApi api, string groupName, {GetFriendlyTypeName(paramType)} {paramName})");
            sb.AppendLine("        {");
            sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
            sb.AppendLine("            if (groupName == null) throw new ArgumentNullException(nameof(groupName));");
            sb.AppendLine($"            var payload = new {fullEventTypeName}");
            sb.AppendLine("            {");
            sb.AppendLine($"                {field.Name} = {paramName}");
            sb.AppendLine("            };");
            sb.AppendLine("            api.PublishForGroup(groupName, payload);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendApiUserEventMethods(StringBuilder sb, Type type)
        {
            var field = GetSinglePublicInstanceField(type);
            if (field == null)
                return;

            var methodSuffix = type.Name;
            var paramType = field.FieldType;
            var paramName = ToCamel(field.Name);
            var fullEventTypeName = $"global::{type.FullName}";

            sb.AppendLine($"        public static void SendUser{methodSuffix}(this IPlayServEventsApi api, string userId, {GetFriendlyTypeName(paramType)} {paramName})");
            sb.AppendLine("        {");
            sb.AppendLine("            if (api == null) throw new ArgumentNullException(nameof(api));");
            sb.AppendLine("            if (userId == null) throw new ArgumentNullException(nameof(userId));");
            sb.AppendLine($"            var payload = new {fullEventTypeName}");
            sb.AppendLine("            {");
            sb.AppendLine($"                {field.Name} = {paramName}");
            sb.AppendLine("            };");
            sb.AppendLine("            api.PublishForUser(userId, payload);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ----------------------------
        // IEventsAdapter extensions (optional)
        // ----------------------------

        private static void AppendAdapterGlobalEventMethods(StringBuilder sb, Type type)
        {
            var field = GetSinglePublicInstanceField(type);
            if (field == null)
                return;

            var methodSuffix = type.Name;
            var paramType = field.FieldType;
            var paramName = ToCamel(field.Name);
            var fullEventTypeName = $"global::{type.FullName}";

            sb.AppendLine($"        public static void Publish{methodSuffix}(this IEventsAdapter adapter, {GetFriendlyTypeName(paramType)} {paramName})");
            sb.AppendLine("        {");
            sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
            sb.AppendLine($"            var payload = new {fullEventTypeName}");
            sb.AppendLine("            {");
            sb.AppendLine($"                {field.Name} = {paramName}");
            sb.AppendLine("            };");
            sb.AppendLine("            adapter.Publish(payload);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine($"        public static IDisposable On{methodSuffix}(this IEventsAdapter adapter, Action<{GetFriendlyTypeName(paramType)}> onReceive)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
            sb.AppendLine("            if (onReceive == null) throw new ArgumentNullException(nameof(onReceive));");
            sb.AppendLine($"            return adapter.Subscribe<{fullEventTypeName}>()");
            sb.AppendLine($"                .Subscribe(e => onReceive(e.{field.Name}));");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendAdapterGroupEventMethods(StringBuilder sb, Type type)
        {
            var field = GetSinglePublicInstanceField(type);
            if (field == null)
                return;

            var methodSuffix = type.Name;
            var paramType = field.FieldType;
            var paramName = ToCamel(field.Name);
            var fullEventTypeName = $"global::{type.FullName}";

            sb.AppendLine($"        public static void PublishGroup{methodSuffix}(this IEventsAdapter adapter, string groupName, {GetFriendlyTypeName(paramType)} {paramName})");
            sb.AppendLine("        {");
            sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
            sb.AppendLine($"            var payload = new {fullEventTypeName}");
            sb.AppendLine("            {");
            sb.AppendLine($"                {field.Name} = {paramName}");
            sb.AppendLine("            };");
            sb.AppendLine("            adapter.PublishForGroup(groupName, payload);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendAdapterUserEventMethods(StringBuilder sb, Type type)
        {
            var field = GetSinglePublicInstanceField(type);
            if (field == null)
                return;

            var methodSuffix = type.Name;
            var paramType = field.FieldType;
            var paramName = ToCamel(field.Name);
            var fullEventTypeName = $"global::{type.FullName}";

            sb.AppendLine($"        public static void PublishUser{methodSuffix}(this IEventsAdapter adapter, string userId, {GetFriendlyTypeName(paramType)} {paramName})");
            sb.AppendLine("        {");
            sb.AppendLine("            if (adapter == null) throw new ArgumentNullException(nameof(adapter));");
            sb.AppendLine($"            var payload = new {fullEventTypeName}");
            sb.AppendLine("            {");
            sb.AppendLine($"                {field.Name} = {paramName}");
            sb.AppendLine("            };");
            sb.AppendLine("            adapter.PublishForUser(userId, payload);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ----------------------------
        // Helpers
        // ----------------------------

        private static FieldInfo? GetSinglePublicInstanceField(Type type)
        {
            var fields = type
                .GetFields(BindingFlags.Instance | BindingFlags.Public)
                .Where(f => !f.IsStatic)
                .ToArray();

            if (fields.Length != 1)
                return null;

            return fields[0];
        }

        private static string ToCamel(string s)
        {
            if (string.IsNullOrWhiteSpace(s))
                return s;

            if (s.Length == 1)
                return char.ToLowerInvariant(s[0]).ToString();

            return char.ToLowerInvariant(s[0]) + s.Substring(1);
        }

        private static string GetFriendlyTypeName(Type type)
        {
            if (!type.IsGenericType)
                return $"global::{type.FullName}";

            var typeDefName = type.GetGenericTypeDefinition().FullName;
            var tickIndex = typeDefName.IndexOf('`');
            if (tickIndex > 0)
                typeDefName = typeDefName.Substring(0, tickIndex);

            var genericArgs = type.GetGenericArguments()
                .Select(GetFriendlyTypeName)
                .ToArray();

            return $"global::{typeDefName}<{string.Join(", ", genericArgs)}>";
        }

        private static void WriteFile(string assetPath, string content)
        {
            var fullPath = Path.GetFullPath(assetPath);
            var directory = Path.GetDirectoryName(fullPath);
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            WriteAllText(fullPath, content, Encoding.UTF8);
        }
    }
}
#nullable restore

#endif
